/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.DanhMucKhuyenMaiBUS;
import qlks.BUS.DichVuBUS;
import qlks.BUS.KhuyenMaiBUS;
import qlks.BUS.SuDungDichVuBUS;
import qlks.DTO.DanhMucKhuyenMai;
import qlks.DTO.DanhMucKhuyenMaiDTO;
import qlks.DTO.DichVu;
import qlks.DTO.DichVuDTO;
import qlks.DTO.KhuyenMai;
import qlks.DTO.KhuyenMaiDTO;
import qlks.DTO.SuDungDichVu;
import qlks.DTO.SuDungDichVuDTO;
import qlks.Model.ModelDanhMucKhuyenMai;
import qlks.Model.ModelDichVu;
import qlks.Model.ModelKhuyenMai;
import qlks.Model.ModelSuDungDichVu;
import sun.text.resources.FormatData;

/**
 *
 * @author Nguyen Tien Dung
 */
public class dichvu extends javax.swing.JPanel {
    //Dich vu
    private static DichVuDTO dvDTO = new DichVuDTO();
    private DichVuBUS dvBUS = new DichVuBUS();
    DichVu dv;
    DefaultTableModel modeldv;
    ArrayList<DichVu> dsdvt;
    ModelDichVu dvMD;
    int rowdv = -1;
    
    //Su dung dich vu
    private static SuDungDichVuDTO sddvDTO = new SuDungDichVuDTO();
    private SuDungDichVuBUS sddvBUS = new SuDungDichVuBUS();
    SuDungDichVu sddv;
    DefaultTableModel modelsddv;
    ArrayList<SuDungDichVu> dssddvt;
    int rowsddv = -1;
    
    //Khuyen mai
    private static KhuyenMaiDTO kmDTO = new KhuyenMaiDTO();
    private KhuyenMaiBUS kmBUS = new KhuyenMaiBUS();
    KhuyenMai km;
    DefaultTableModel modelkm;
    ArrayList<KhuyenMai> dskm;
    int rowkm = -1;
    
    //DanhMucKhuyenMai
    private static DanhMucKhuyenMaiDTO dmkmDTO = new DanhMucKhuyenMaiDTO();
    private DanhMucKhuyenMaiBUS dmkmBUS = new DanhMucKhuyenMaiBUS();
    DanhMucKhuyenMai dmkm;
    DefaultTableModel modeldmkm;
    ArrayList<DanhMucKhuyenMai> dsdmkm;
    int rowdmkm = -1;
    
    //Bien static tu Hop Dong Thue phong
    static String sddvSoHopDongThuePhong = "";
    static String dmkmSoHopDongThuePhong = "";
    
    
    ImageIcon imageIcon;
    Image image;
    /**
     * Creates new form dichvu
     */
    public dichvu() {
        initComponents();
        //dich vu
        modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
        tbDV.setModel(modeldv);
        //su dung dich vu
            //Set background cho label
            lbCong.setOpaque(true);
            lbSL.setOpaque(true);
            lbTru.setOpaque(true);
        if(sddvSoHopDongThuePhong.length()>0){
            tfSDDVSHD.setText(sddvSoHopDongThuePhong);
            sddvSoHopDongThuePhong = "";
        }
        modelsddv = new ModelSuDungDichVu(sddvDTO.docDanhSachSuDungDichVu()).getModel();
        tbSDDV.setModel(modelsddv);
        //khuyen mai
        modelkm = new ModelKhuyenMai(kmDTO.docDanhSachKhuyenMai()).getModel();
        tbKM.setModel(modelkm);
        //danh muc khuyen mai
        if(dmkmSoHopDongThuePhong.length()>0){
            tbPane.setSelectedIndex(1);
            tfDMKMSHD.setText(dmkmSoHopDongThuePhong);
            dmkmSoHopDongThuePhong = "";
        }
        modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.docDanhSachDanhMucKhuyenMai()).getModel();
        tbDMKM.setModel(modeldmkm);
        tfDMKMNKM.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }
    
    public void setIcon(){
        imageIcon = new ImageIcon(getClass().getResource("/qlks/hinh/search.png"));
        image = imageIcon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(image);
        btDVTim.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDVMDV = new javax.swing.JTextField();
        tfDVTDV = new javax.swing.JTextField();
        tfDVGDV = new javax.swing.JTextField();
        btThenDV = new javax.swing.JButton();
        btSuaDV = new javax.swing.JButton();
        btDVXoa = new javax.swing.JButton();
        btClearDV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDV = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        tfDVMMH = new javax.swing.JTextField();
        btDVTim = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSDDV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfSDDVSHD = new javax.swing.JTextField();
        tfSDDVMDV = new javax.swing.JTextField();
        tfSDDVDG = new javax.swing.JTextField();
        btSDDVTim = new javax.swing.JButton();
        btSDDVThem = new javax.swing.JButton();
        btSDDVXoa = new javax.swing.JButton();
        btXoaSDDV = new javax.swing.JButton();
        lbCong = new javax.swing.JLabel();
        lbSL = new javax.swing.JLabel();
        lbTru = new javax.swing.JLabel();
        lbTT = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfKMMGG = new javax.swing.JTextField();
        tfKMTCT = new javax.swing.JTextField();
        tfKMTGBD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btKMThem = new javax.swing.JButton();
        btKMSua = new javax.swing.JButton();
        btKMXoa = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKM = new javax.swing.JTable();
        tfKMTGKT = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfKMG = new javax.swing.JTextField();
        btCTKMTim = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDMKM = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfDMKMMKM = new javax.swing.JTextField();
        tfDMKMSHD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfDMKMNKM = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDMKMND = new javax.swing.JTextArea();
        btDMKMThem = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfDMKMGG = new javax.swing.JTextField();
        btDMKMSua = new javax.swing.JButton();
        btDMKMxoa = new javax.swing.JButton();
        cbDMKMLKM = new javax.swing.JComboBox<>();
        lbDMKMNgay = new javax.swing.JLabel();

        tbPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbPaneStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "SỬ DỤNG DỊCH VỤ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)), "Thông tin dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel5.setToolTipText("");

        jLabel1.setText("Mã dịch vụ");

        jLabel2.setText("Tên dịch vụ");

        jLabel3.setText("Giá dich vụ");

        tfDVMDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDVMDVKeyPressed(evt);
            }
        });

        tfDVTDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDVTDVActionPerformed(evt);
            }
        });
        tfDVTDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDVTDVKeyPressed(evt);
            }
        });

        tfDVGDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDVGDVKeyPressed(evt);
            }
        });

        btThenDV.setBackground(new java.awt.Color(0, 153, 153));
        btThenDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btThenDV.setText("Thêm");
        btThenDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThenDVActionPerformed(evt);
            }
        });

        btSuaDV.setBackground(new java.awt.Color(0, 153, 153));
        btSuaDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btSuaDV.setText("Sửa");
        btSuaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaDVActionPerformed(evt);
            }
        });

        btDVXoa.setBackground(new java.awt.Color(0, 153, 153));
        btDVXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btDVXoa.setText("Xóa");
        btDVXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDVXoaActionPerformed(evt);
            }
        });

        btClearDV.setBackground(new java.awt.Color(0, 153, 153));
        btClearDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btClearDV.setText("Clear");
        btClearDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearDVActionPerformed(evt);
            }
        });

        tbDV.setBackground(new java.awt.Color(255, 255, 204));
        tbDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá dịch vụ"
            }
        ));
        tbDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDVMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbDV);

        jLabel23.setText("Mã  mặt hàng");

        tfDVMMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDVMMHActionPerformed(evt);
            }
        });

        btDVTim.setBackground(new java.awt.Color(0, 153, 153));
        btDVTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        btDVTim.setText("Tìm");
        btDVTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDVTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btThenDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSuaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btDVXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDVTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btClearDV))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel23))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDVTDV, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(tfDVGDV)
                            .addComponent(tfDVMDV)
                            .addComponent(tfDVMMH))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDVMDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDVTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDVGDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfDVMMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThenDV)
                    .addComponent(btSuaDV))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btDVXoa)
                        .addComponent(btClearDV))
                    .addComponent(btDVTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách sử dụng dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(255, 255, 0))); // NOI18N

        tbSDDV.setBackground(new java.awt.Color(255, 255, 204));
        tbSDDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã dịch vu", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tbSDDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSDDVMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbSDDV);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel4.setText("Số hợp đồng");

        jLabel5.setText("Mã dịch vụ ");

        jLabel6.setText("Thành tiền");

        jLabel7.setText("Đơn giá");

        jLabel8.setText("Số lượng");

        tfSDDVSHD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSDDVSHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSDDVSHDKeyPressed(evt);
            }
        });

        tfSDDVMDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSDDVMDV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSDDVMDVFocusLost(evt);
            }
        });
        tfSDDVMDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSDDVMDVActionPerformed(evt);
            }
        });
        tfSDDVMDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSDDVMDVKeyPressed(evt);
            }
        });

        tfSDDVDG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSDDVDG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSDDVDGFocusLost(evt);
            }
        });
        tfSDDVDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSDDVDGKeyPressed(evt);
            }
        });

        btSDDVTim.setBackground(new java.awt.Color(0, 153, 153));
        btSDDVTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        btSDDVTim.setText("Tìm");
        btSDDVTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSDDVTimActionPerformed(evt);
            }
        });

        btSDDVThem.setBackground(new java.awt.Color(0, 153, 153));
        btSDDVThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btSDDVThem.setText("Thêm");
        btSDDVThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSDDVThemActionPerformed(evt);
            }
        });

        btSDDVXoa.setBackground(new java.awt.Color(0, 153, 153));
        btSDDVXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btSDDVXoa.setText("Sửa");
        btSDDVXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSDDVXoaActionPerformed(evt);
            }
        });

        btXoaSDDV.setBackground(new java.awt.Color(0, 153, 153));
        btXoaSDDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btXoaSDDV.setText("Xóa");
        btXoaSDDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaSDDVActionPerformed(evt);
            }
        });

        lbCong.setBackground(new java.awt.Color(255, 255, 255));
        lbCong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCong.setText("+");
        lbCong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbCong.setOpaque(true);
        lbCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCongMouseReleased(evt);
            }
        });

        lbSL.setBackground(new java.awt.Color(255, 255, 255));
        lbSL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSL.setText("0");
        lbSL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbSL.setOpaque(true);

        lbTru.setBackground(new java.awt.Color(255, 255, 255));
        lbTru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTru.setText("-");
        lbTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbTru.setOpaque(true);
        lbTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTruMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbTruMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbTruMouseReleased(evt);
            }
        });

        lbTT.setBackground(new java.awt.Color(255, 255, 255));
        lbTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbTT.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/tick.png"))); // NOI18N
        jButton2.setText("Chọn hợp đồng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSDDVSHD)
                    .addComponent(tfSDDVDG, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(tfSDDVMDV))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTru, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSL, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btSDDVTim, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btSDDVThem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSDDVXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btXoaSDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfSDDVSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(btSDDVThem)
                    .addComponent(lbCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfSDDVMDV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(lbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btSDDVXoa)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfSDDVDG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSDDVTim)
                    .addComponent(btXoaSDDV)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tbPane.addTab("Dịch vu", jPanel1);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "DANH MỤC KHUYẾN MÃI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)), "Chương trình khuyến mãi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel11.setText("Mã giảm giá");

        jLabel12.setText("Tên chương trình");

        jLabel13.setText("Thời gian bắt đầu");

        tfKMMGG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKMMGGKeyPressed(evt);
            }
        });

        tfKMTCT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKMTCTKeyPressed(evt);
            }
        });

        tfKMTGBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKMTGBDActionPerformed(evt);
            }
        });
        tfKMTGBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKMTGBDKeyPressed(evt);
            }
        });

        jLabel15.setText("Thời gian kết thúc");

        btKMThem.setBackground(new java.awt.Color(0, 153, 153));
        btKMThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btKMThem.setText("Thêm");
        btKMThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKMThemActionPerformed(evt);
            }
        });

        btKMSua.setBackground(new java.awt.Color(0, 153, 153));
        btKMSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btKMSua.setText("Sửa");
        btKMSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKMSuaActionPerformed(evt);
            }
        });

        btKMXoa.setBackground(new java.awt.Color(0, 153, 153));
        btKMXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btKMXoa.setText("Xóa");
        btKMXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKMXoaActionPerformed(evt);
            }
        });

        btClear.setBackground(new java.awt.Color(0, 153, 153));
        btClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        tbKM.setBackground(new java.awt.Color(255, 255, 204));
        tbKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID giảm giá", "Mã sản phẩm", "Mã dịch vụ", "Nội dung "
            }
        ));
        tbKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbKMMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbKM);

        tfKMTGKT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKMTGKTKeyPressed(evt);
            }
        });

        jLabel22.setText("Giảm (%) ");

        btCTKMTim.setBackground(new java.awt.Color(0, 153, 153));
        btCTKMTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        btCTKMTim.setText("Tìm");
        btCTKMTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCTKMTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfKMMGG, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addComponent(tfKMTCT, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfKMTGBD, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfKMTGKT, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tfKMG, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCTKMTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKMXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKMSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKMThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfKMMGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfKMTCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btKMThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btKMSua)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCTKMTim))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfKMTGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(btKMXoa))
                            .addGap(18, 18, 18)
                            .addComponent(tfKMTGKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfKMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btClear)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách khuyến mãi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel10.setToolTipText("");

        tbDMKM.setBackground(new java.awt.Color(255, 255, 204));
        tbDMKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Thời gian", "Ghi chú", "Mức ưu đãi"
            }
        ));
        tbDMKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDMKMMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbDMKM);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel9.setText("Số hợp đồng ");

        jLabel17.setText("Mã khuyến mãi ");

        jLabel18.setText("Loại khuyến mãi ");

        tfDMKMMKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDMKMMKMKeyPressed(evt);
            }
        });

        tfDMKMSHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDMKMSHDKeyPressed(evt);
            }
        });

        jLabel19.setText("Ngày khuyến mãi ");

        tfDMKMNKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDMKMNKMActionPerformed(evt);
            }
        });
        tfDMKMNKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDMKMNKMKeyPressed(evt);
            }
        });

        jLabel20.setText("Nội dung ");

        taDMKMND.setColumns(20);
        taDMKMND.setRows(5);
        jScrollPane5.setViewportView(taDMKMND);

        btDMKMThem.setBackground(new java.awt.Color(0, 153, 153));
        btDMKMThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btDMKMThem.setText("Thêm");
        btDMKMThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDMKMThemActionPerformed(evt);
            }
        });

        jLabel21.setText("Giảm giá ");

        btDMKMSua.setBackground(new java.awt.Color(0, 153, 153));
        btDMKMSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btDMKMSua.setText("Sửa");
        btDMKMSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDMKMSuaActionPerformed(evt);
            }
        });

        btDMKMxoa.setBackground(new java.awt.Color(0, 153, 153));
        btDMKMxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btDMKMxoa.setText("Xóa");
        btDMKMxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDMKMxoaActionPerformed(evt);
            }
        });

        cbDMKMLKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng", "Phòng", "Dịch vụ" }));
        cbDMKMLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDMKMLKMActionPerformed(evt);
            }
        });

        lbDMKMNgay.setBackground(new java.awt.Color(255, 255, 255));
        lbDMKMNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDMKMNgay.setText("...");
        lbDMKMNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbDMKMNgay.setOpaque(true);
        lbDMKMNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDMKMNgayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDMKMNgayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbDMKMNgayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbDMKMNgayMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDMKMSHD)
                    .addComponent(tfDMKMMKM)
                    .addComponent(cbDMKMLKM, 0, 123, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfDMKMNKM, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDMKMNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfDMKMGG)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btDMKMThem)
                        .addGap(6, 6, 6)
                        .addComponent(btDMKMSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDMKMxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfDMKMSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfDMKMNKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(lbDMKMNgay))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfDMKMMKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfDMKMGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(btDMKMThem)
                    .addComponent(btDMKMSua)
                    .addComponent(btDMKMxoa)
                    .addComponent(cbDMKMLKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tbPane.addTab("Danh mục khuyến mãi", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbPane, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btKMXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKMXoaActionPerformed
        if(tfKMMGG.getText().length()>0){
            if(kmBUS.xoaKhuyenMai(kmDTO, tfKMMGG.getText())){
                modelkm = new ModelKhuyenMai(kmDTO.docDanhSachKhuyenMai()).getModel();
                tbKM.setModel(modelkm);
            }
        }
    }//GEN-LAST:event_btKMXoaActionPerformed

    private void btSDDVTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSDDVTimActionPerformed

        sddv = new SuDungDichVu();
        sddv.setSoHopDongTHuePhong(tfSDDVSHD.getText());
        sddv.setMaDichVu(tfSDDVMDV.getText());
        if(tfSDDVDG.getText().length()>0){
            if(sddv.setDonGia(tfSDDVDG.getText()) == false){
                return;
            }
        }else{
            sddv.setDonGia("-1");
        }
        sddv.setSoLuong(Integer.valueOf(lbSL.getText()));
        if(lbTT.getText().length()>0){
            sddv.setThanhTien(Integer.valueOf(lbTT.getText()));
        }else{
            sddv.setThanhTien(-1);
        }
            
        modelsddv = new ModelSuDungDichVu(sddvDTO.timSuDungDichVu(sddv)).getModel();
        tbSDDV.setModel(modelsddv);
    }//GEN-LAST:event_btSDDVTimActionPerformed

    private void tbDVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDVMousePressed
        rowdv = tbDV.getSelectedRow();
        
        tfDVMDV.setText(modeldv.getValueAt(rowdv, 0).toString());
        tfSDDVMDV.setText(modeldv.getValueAt(rowdv, 0).toString());
        tfDVTDV.setText(modeldv.getValueAt(rowdv, 1).toString());
        tfDVGDV.setText(modeldv.getValueAt(rowdv, 2).toString());
        tfSDDVDG.setText(modeldv.getValueAt(rowdv, 2).toString());
        tfDVMMH.setText(modeldv.getValueAt(rowdv, 3).toString());
        lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
        
        modelsddv = new ModelSuDungDichVu(sddvDTO.danhSachMaDichVu(modeldv.getValueAt(rowdv, 0).toString())).getModel();
        tbSDDV.setModel(modelsddv);
    }//GEN-LAST:event_tbDVMousePressed

    private void btClearDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearDVActionPerformed
        tfDVMDV.setText("");
        tfDVTDV.setText("");
        tfDVGDV.setText(""); 
        tfDVMMH.setText("");
        
        modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
        tbDV.setModel(modeldv);
        
        tfSDDVSHD.setText("");
        tfSDDVMDV.setText("");
        tfSDDVDG.setText("");
        lbSL.setText("0");
        lbTT.setText("");
        
        modelsddv = new ModelSuDungDichVu(sddvDTO.docDanhSachSuDungDichVu()).getModel();
        tbSDDV.setModel(modelsddv);
    }//GEN-LAST:event_btClearDVActionPerformed

    private void btThenDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThenDVActionPerformed
        if(tfDVMDV.getText().length()>0&&tfDVTDV.getText().length()>0&&tfDVGDV.getText().length()>0){
            dv = new DichVu();
            dv.setMaDichVu(tfDVMDV.getText());
            dv.setTenDichVu(tfDVTDV.getText());
            if(dv.setDonGia(tfDVGDV.getText()) == false){
                return;
            }
            dv.setMatHang(tfDVMMH.getText());

            if(dvBUS.themDichVu(dvDTO, dv)){
                modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
                tbDV.setModel(modeldv);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btThenDVActionPerformed

    private void btSuaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaDVActionPerformed
        if(tfDVMDV.getText().length()>0&&tfDVTDV.getText().length()>0&&tfDVGDV.getText().length()>0){
            dv = new DichVu();
            dv.setMaDichVu(tfDVMDV.getText());
            dv.setTenDichVu(tfDVTDV.getText());
            if(dv.setDonGia(tfDVGDV.getText()) == false){
                return;
            }
            dv.setMatHang(tfDVMMH.getText());

            if(dvBUS.suaDichVu(dvDTO, dv)){
                Vector vt = new Vector();
                vt.add(dv.getMaDichVu());
                vt.add(dv.getTenDichVu());
                vt.add(dv.getDonGia());
                
                modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
                tbDV.setModel(modeldv);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btSuaDVActionPerformed

    private void tbPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbPaneStateChanged
        if(tbPane.getSelectedIndex()==0){
            modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
            tbDV.setModel(modeldv);
            
            modelsddv = new ModelSuDungDichVu(sddvDTO.docDanhSachSuDungDichVu()).getModel();
            tbSDDV.setModel(modelsddv);
        }else{
            
        }
    }//GEN-LAST:event_tbPaneStateChanged

    private void tfSDDVMDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSDDVMDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSDDVMDVActionPerformed

    private void lbTruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTruMouseEntered
        lbTru.setBackground(Color.yellow);
    }//GEN-LAST:event_lbTruMouseEntered

    private void lbTruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTruMouseExited
        lbTru.setBackground(Color.white);
    }//GEN-LAST:event_lbTruMouseExited

    private void lbCongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCongMouseEntered
        lbCong.setBackground(Color.yellow);
    }//GEN-LAST:event_lbCongMouseEntered

    private void lbCongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCongMouseExited
        lbCong.setBackground(Color.white);
    }//GEN-LAST:event_lbCongMouseExited

    private void lbTruMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTruMousePressed
        lbTru.setBackground(Color.RED);
        if(Integer.valueOf(lbSL.getText())>0){
            lbSL.setText((Integer.valueOf(lbSL.getText())-1)+"");
            if(tfSDDVDG.getText().length()>0){
                lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
            }
        }
    }//GEN-LAST:event_lbTruMousePressed

    private void lbCongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCongMousePressed
        lbCong.setBackground(Color.RED);
        lbSL.setText((Integer.valueOf(lbSL.getText())+1)+"");
        if(tfSDDVDG.getText().length()>0){
            lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
        }
    }//GEN-LAST:event_lbCongMousePressed

    private void tbSDDVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSDDVMousePressed
        rowsddv = tbSDDV.getSelectedRow();
        
        tfSDDVSHD.setText(modelsddv.getValueAt(rowsddv, 0).toString());
        String mdv = "";
        for(DichVu dvt: dvDTO.docDanhSachDichVu()){
            if(dvt.getTenDichVu().compareTo(modelsddv.getValueAt(rowsddv, 1).toString())==0){
                mdv = dvt.getMaDichVu();
                break;
            }
        }
        tfSDDVMDV.setText(mdv);
        tfSDDVDG.setText(modelsddv.getValueAt(rowsddv, 2).toString());
        lbSL.setText(modelsddv.getValueAt(rowsddv, 3).toString());
        lbTT.setText(modelsddv.getValueAt(rowsddv, 4).toString());
    }//GEN-LAST:event_tbSDDVMousePressed

    private void btSDDVThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSDDVThemActionPerformed
        if(tfSDDVSHD.getText().length()>0&&tfSDDVMDV.getText().length()>0&&
                tfSDDVDG.getText().length()>0&&lbSL.getText().length()>0&&lbTT.getText().length()>0){

            sddv = new SuDungDichVu();
            sddv.setSoHopDongTHuePhong(tfSDDVSHD.getText());
            sddv.setMaDichVu(tfSDDVMDV.getText());
            if(sddv.setDonGia(tfSDDVDG.getText()) == false){
                return;
            }
            sddv.setSoLuong(Integer.valueOf(lbSL.getText()));
            sddv.setThanhTien(Integer.valueOf(lbTT.getText()));
            
            if(sddvBUS.themSuDungDichVu(sddvDTO, sddv)){
                Vector vt = new Vector();
                String tdv = "";
                for(DichVu dvt: dvDTO.docDanhSachDichVu()){
                    if(dvt.getMaDichVu().compareTo(tfSDDVMDV.getText())==0){
                        tdv = dvt.getTenDichVu();
                        break;
                    }
                }
                vt.add(tfSDDVSHD.getText());
                vt.add(tdv);
                vt.add(tfSDDVDG.getText());
                vt.add(lbSL.getText());
                vt.add(lbTT.getText());
                
                modelsddv.addRow(vt);
            }
        }
    }//GEN-LAST:event_btSDDVThemActionPerformed

    private void tfSDDVDGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSDDVDGFocusLost
        if(tfSDDVDG.getText().length()>0){
            try{
                Integer.parseInt(tfSDDVDG.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Đơn giá là số");
                return;
            }
            lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
        }
        
    }//GEN-LAST:event_tfSDDVDGFocusLost

    private void tfSDDVMDVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSDDVMDVFocusLost
        if(tfSDDVMDV.getText().length()>0){
            for(DichVu dvt: dvDTO.docDanhSachDichVu()){
                if(dvt.getMaDichVu().compareTo(tfSDDVMDV.getText())==0){
                    tfSDDVDG.setText(dvt.getDonGia()+"");
                    lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
                }
            }
        }
    }//GEN-LAST:event_tfSDDVMDVFocusLost

    private void btSDDVXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSDDVXoaActionPerformed
        if(tfSDDVSHD.getText().length()>0&&tfSDDVMDV.getText().length()>0&&
                tfSDDVDG.getText().length()>0&&lbSL.getText().length()>0&&lbTT.getText().length()>0){

            sddv = new SuDungDichVu();
            sddv.setSoHopDongTHuePhong(tfSDDVSHD.getText());
            sddv.setMaDichVu(tfSDDVMDV.getText());
            if(sddv.setDonGia(tfSDDVDG.getText()) == false){
                return;
            }
            sddv.setSoLuong(Integer.valueOf(lbSL.getText()));
            sddv.setThanhTien(Integer.valueOf(lbTT.getText()));
            
            if(sddvBUS.suaSuDungDichVu(sddvDTO, sddv)){
                modelsddv = new ModelSuDungDichVu(sddvDTO.docDanhSachSuDungDichVu()).getModel();
                tbSDDV.setModel(modelsddv);
                
            }
        }
    }//GEN-LAST:event_btSDDVXoaActionPerformed

    private void btDMKMxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDMKMxoaActionPerformed
        if(tfDMKMSHD.getText().length()>0&&tfDMKMMKM.getText().length()>0){
            dmkm = new DanhMucKhuyenMai();
            dmkm.setSoHopDongThuePhong(tfDMKMSHD.getText());
            dmkm.setMaChuongTrinhKhuyenMai(tfDMKMMKM.getText());
            if(dmkmBUS.xoaDanhMucKhuyenMai(dmkmDTO, dmkm)){
                modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.docDanhSachDanhMucKhuyenMai()).getModel();
                tbDMKM.setModel(modeldmkm);
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Vui lòng nhập số hợp đồng và mã khuyến mãi");
        }
    }//GEN-LAST:event_btDMKMxoaActionPerformed

    private void tfKMTGBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKMTGBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKMTGBDActionPerformed

    private void tbKMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKMMousePressed
        rowkm = tbKM.getSelectedRow();
        
        tfKMMGG.setText(modelkm.getValueAt(rowkm, 0).toString());
        tfDMKMMKM.setText(modelkm.getValueAt(rowkm, 0).toString());
        tfKMTCT.setText(modelkm.getValueAt(rowkm, 1).toString());
        tfKMTGBD.setText(modelkm.getValueAt(rowkm, 2).toString());
        tfKMTGKT.setText(modelkm.getValueAt(rowkm, 3).toString());
        tfKMG.setText(modelkm.getValueAt(rowkm, 4).toString());
        tfDMKMGG.setText(modelkm.getValueAt(rowkm, 4).toString());
        
        modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.getMaKhuyenMai(modelkm.getValueAt(rowkm, 0).toString())).getModel();
        tbDMKM.setModel(modeldmkm);
    }//GEN-LAST:event_tbKMMousePressed

    private void btKMThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKMThemActionPerformed
        if(tfKMMGG.getText().length()>0&&tfKMTCT.getText().length()>0&&tfKMTGBD.getText().length()>0&&
                tfKMTGKT.getText().length()>0&&tfKMG.getText().length()>0){
            km = new KhuyenMai();
            km.setMaChuongTrinhKhuyenMai(tfKMMGG.getText());
            km.setTenChuongTrinhKhuyenMai(tfKMTCT.getText());
            if(km.setThoiGianBatDauKT(tfKMTGBD.getText()) == false){
                return;
            }
            if(km.setTHoiGianKetThucKT(tfKMTGKT.getText(),tfKMTGBD.getText()) == false){
                return;
            }
            if(km.setGiamGia(tfKMG.getText()) == false){
                return;
            }
            
            if(kmBUS.themKhuyenMai(kmDTO, km)){
                modelkm = new ModelKhuyenMai(kmDTO.docDanhSachKhuyenMai()).getModel();
                tbKM.setModel(modelkm);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btKMThemActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        tfKMMGG.setText("");
        tfKMTCT.setText("");
        tfKMTGBD.setText("");
        tfKMTGKT.setText("");
        tfKMG.setText("");
        modelkm = new ModelKhuyenMai(kmDTO.docDanhSachKhuyenMai()).getModel();
        tbKM.setModel(modelkm);
        
        tfDMKMSHD.setText("");
        tfDMKMGG.setText("");
        cbDMKMLKM.setSelectedIndex(0);
        tfDMKMNKM.setText("");
        tfDMKMMKM.setText("");
        taDMKMND.setText("");
        modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.docDanhSachDanhMucKhuyenMai()).getModel();
        tbDMKM.setModel(modeldmkm);
    }//GEN-LAST:event_btClearActionPerformed

    private void btKMSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKMSuaActionPerformed
        if(tfKMMGG.getText().length()>0&&tfKMTCT.getText().length()>0&&tfKMTGBD.getText().length()>0&&
                tfKMTGKT.getText().length()>0&&tfKMG.getText().length()>0){
            km = new KhuyenMai();
            km.setMaChuongTrinhKhuyenMai(tfKMMGG.getText());
            km.setTenChuongTrinhKhuyenMai(tfKMTCT.getText());
            if(km.setThoiGianBatDauKT(tfKMTGBD.getText()) == false){
                return;
            }
            if(km.setTHoiGianKetThucKT(tfKMTGKT.getText(),tfKMTGBD.getText()) == false){
                return;
            }
            if(km.setGiamGia(tfKMG.getText()) == false){
                return;
            }
            
            if(kmBUS.suaKhuyenMai(kmDTO, km)){
                modelkm = new ModelKhuyenMai(kmDTO.docDanhSachKhuyenMai()).getModel();
                tbKM.setModel(modelkm);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btKMSuaActionPerformed

    private void tbDMKMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDMKMMousePressed
        rowdmkm = tbDMKM.getSelectedRow();
        
        tfDMKMSHD.setText(modeldmkm.getValueAt(rowdmkm, 0).toString());
        tfDMKMMKM.setText(modeldmkm.getValueAt(rowdmkm, 1).toString());
        if(modeldmkm.getValueAt(rowdmkm, 2).toString().compareTo("Khách hàng")==0){
            cbDMKMLKM.setSelectedIndex(0);
        }else{
            if(modeldmkm.getValueAt(rowdmkm, 2).toString().compareTo("Phòng")==0){
                cbDMKMLKM.setSelectedIndex(1);
            }else{
                if(modeldmkm.getValueAt(rowdmkm, 2).toString().compareTo("Dịch vụ")==0){
                    cbDMKMLKM.setSelectedIndex(2);
                }
            }
        }
        tfDMKMNKM.setText(modeldmkm.getValueAt(rowdmkm, 3).toString());
        tfDMKMGG.setText(modeldmkm.getValueAt(rowdmkm, 4).toString());
        taDMKMND.setText(modeldmkm.getValueAt(rowdmkm, 5).toString());
    }//GEN-LAST:event_tbDMKMMousePressed

    private void tfDMKMNKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDMKMNKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDMKMNKMActionPerformed

    private void lbDMKMNgayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDMKMNgayMouseEntered
        lbDMKMNgay.setBackground(Color.YELLOW);
    }//GEN-LAST:event_lbDMKMNgayMouseEntered

    private void lbDMKMNgayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDMKMNgayMouseExited
        lbDMKMNgay.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbDMKMNgayMouseExited

    private void lbDMKMNgayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDMKMNgayMousePressed
        lbDMKMNgay.setBackground(Color.RED);
        
        tfDMKMNKM.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }//GEN-LAST:event_lbDMKMNgayMousePressed

    private void lbDMKMNgayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDMKMNgayMouseReleased
        lbDMKMNgay.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbDMKMNgayMouseReleased

    private void btDMKMThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDMKMThemActionPerformed
        if(tfDMKMSHD.getText().length()>0&&tfDMKMMKM.getText().length()>0&&tfDMKMNKM.getText().length()>0&&
                tfDMKMGG.getText().length()>0){
            dmkm = new DanhMucKhuyenMai();
            dmkm.setSoHopDongThuePhong(tfDMKMSHD.getText());
            dmkm.setMaChuongTrinhKhuyenMai(tfDMKMMKM.getText());
            dmkm.setLoaiKhuyenMai(cbDMKMLKM.getSelectedItem().toString());
            String ngayBatDau = "";
            String ngayKetThuc = "";
            for(KhuyenMai km: new KhuyenMaiDTO().docDanhSachKhuyenMai()){
                if(km.getMaChuongTrinhKhuyenMai().compareTo(tfDMKMMKM.getText())==0){
                    ngayBatDau = km.getThoiGianBatDau();
                    ngayKetThuc = km.getTHoiGianKetThuc();
                }
            }
            if(dmkm.setNgayKhuyenMaiKT(tfDMKMNKM.getText(),ngayBatDau,ngayKetThuc) == false){
                return;
            }
            dmkm.setNoiDunngKhuyenMai(taDMKMND.getText());
            if(dmkm.setGiamGia(tfDMKMGG.getText()) == false){
                return;
            }
            
            if(dmkmBUS.themDanhMucKhuyenMai(dmkmDTO, dmkm)){
                Vector vt = new Vector();
                vt.add(dmkm.getSoHopDongThuePhong());
                vt.add(dmkm.getMaChuongTrinhKhuyenMai());
                vt.add(dmkm.getLoaiKhuyenMai());
                vt.add(dmkm.getNgayKhuyenMai());
                vt.add(dmkm.getGiamGia());
                vt.add(dmkm.getNoiDunngKhuyenMai());
                
                modeldmkm.addRow(vt);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btDMKMThemActionPerformed

    private void lbTruMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTruMouseReleased
        lbTru.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbTruMouseReleased

    private void lbCongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCongMouseReleased
        lbCong.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbCongMouseReleased

    private void btDMKMSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDMKMSuaActionPerformed
        if(tfDMKMSHD.getText().length()>0&&tfDMKMMKM.getText().length()>0&&tfDMKMNKM.getText().length()>0&&
                tfDMKMGG.getText().length()>0){
            dmkm = new DanhMucKhuyenMai();
            dmkm.setSoHopDongThuePhong(tfDMKMSHD.getText());
            dmkm.setMaChuongTrinhKhuyenMai(tfDMKMMKM.getText());
            dmkm.setLoaiKhuyenMai(cbDMKMLKM.getSelectedItem().toString());
            String ngayBatDau = "";
            String ngayKetThuc = "";
            for(KhuyenMai km: new KhuyenMaiDTO().docDanhSachKhuyenMai()){
                if(km.getMaChuongTrinhKhuyenMai().compareTo(tfDMKMMKM.getText())==0){
                    ngayBatDau = km.getThoiGianBatDau();
                    ngayKetThuc = km.getTHoiGianKetThuc();
                }
            }
            if(dmkm.setNgayKhuyenMaiKT(tfDMKMNKM.getText(),ngayBatDau,ngayKetThuc) == false){
                return;
            }
            dmkm.setNoiDunngKhuyenMai(taDMKMND.getText());
            if(dmkm.setGiamGia(tfDMKMGG.getText()) == false){
                return;
            }
            
            if(dmkmBUS.suaDanhMucKhuyenMai(dmkmDTO, dmkm)){
                Vector vt = new Vector();
                vt.add(dmkm.getSoHopDongThuePhong());
                vt.add(dmkm.getMaChuongTrinhKhuyenMai());
                vt.add(dmkm.getLoaiKhuyenMai());
                vt.add(dmkm.getNgayKhuyenMai());
                vt.add(dmkm.getGiamGia());
                vt.add(dmkm.getNoiDunngKhuyenMai());
                
                modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.docDanhSachDanhMucKhuyenMai()).getModel();
                tbDMKM.setModel(modeldmkm);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btDMKMSuaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        phong.hdpSuDungDichVu = true;
        MENUFORM.formatButton(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btDVXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDVXoaActionPerformed
        if(tfDVMDV.getText().length()>0){
            if(dvBUS.xoaDichVu(dvDTO, tfDVMDV.getText())){
                modeldv = new ModelDichVu(dvDTO.docDanhSachDichVu()).getModel();
                tbDV.setModel(modeldv);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã dịch vụ");
        }
    }//GEN-LAST:event_btDVXoaActionPerformed

    private void tfDVMMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDVMMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDVMMHActionPerformed

    private void btXoaSDDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaSDDVActionPerformed
        if(tfSDDVSHD.getText().length()>0 && tfSDDVMDV.getText().length()>0){
            sddv = new SuDungDichVu();
            sddv.setSoHopDongTHuePhong(tfSDDVSHD.getText());
            sddv.setMaDichVu(tfSDDVMDV.getText());
            if(sddvBUS.xoaSuDungDichVu(sddvDTO, sddv)){
                modelsddv = new ModelSuDungDichVu(sddvDTO.docDanhSachSuDungDichVu()).getModel();
                tbSDDV.setModel(modelsddv);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp đồng và mã dịch vụ");
        }
    }//GEN-LAST:event_btXoaSDDVActionPerformed

    private void btDVTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDVTimActionPerformed
        dv = new DichVu();
        dv.setMaDichVu(tfDVMDV.getText());
        dv.setTenDichVu(tfDVTDV.getText());
        if(tfDVGDV.getText().length()>0){
            if(dv.setDonGia(tfDVGDV.getText()) == false){
                return;
            }
        }else{
            dv.setDonGia("-1");
        }
        
        dv.setMatHang(tfDVMMH.getText());
        
        modeldv = new ModelDichVu(dvDTO.timDichVu(dv)).getModel();
        tbDV.setModel(modeldv);
    }//GEN-LAST:event_btDVTimActionPerformed

    private void btCTKMTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCTKMTimActionPerformed
        int giamGia = 0;
        try{
            giamGia = Integer.parseInt(tfKMG.getText());
        }catch(Exception e){
            giamGia = -1;
        }
        
        km = new KhuyenMai();
        km.setMaChuongTrinhKhuyenMai(tfKMMGG.getText());
        km.setTenChuongTrinhKhuyenMai(tfKMTCT.getText());
        km.setThoiGianBatDau(tfKMTGBD.getText());
        km.setTHoiGianKetThuc(tfKMTGKT.getText());
        km.setGiamGia(giamGia);
        
        modelkm = new ModelKhuyenMai(kmDTO.timKhuyenMai(km)).getModel();
        tbKM.setModel(modelkm);
    }//GEN-LAST:event_btCTKMTimActionPerformed

    private void cbDMKMLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDMKMLKMActionPerformed
        if(cbDMKMLKM.isFocusOwner()){
            modeldmkm = new ModelDanhMucKhuyenMai(dmkmDTO.locLoaiKhuyenMai(cbDMKMLKM.getSelectedItem().toString())).getModel();
            tbDMKM.setModel(modeldmkm);
        }
    }//GEN-LAST:event_cbDMKMLKMActionPerformed

    private void tfDVMDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDVMDVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDVTDV.requestFocus();
        }
    }//GEN-LAST:event_tfDVMDVKeyPressed

    private void tfDVTDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDVTDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDVTDVActionPerformed

    private void tfDVTDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDVTDVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDVGDV.requestFocus();
        }
    }//GEN-LAST:event_tfDVTDVKeyPressed

    private void tfDVGDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDVGDVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDVMMH.requestFocus();
        }
    }//GEN-LAST:event_tfDVGDVKeyPressed

    private void tfSDDVSHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSDDVSHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfSDDVMDV.requestFocus();
        }
    }//GEN-LAST:event_tfSDDVSHDKeyPressed

    private void tfSDDVMDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSDDVMDVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfSDDVDG.requestFocus();
        }
    }//GEN-LAST:event_tfSDDVMDVKeyPressed

    private void tfKMMGGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKMMGGKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKMTCT.requestFocus();
        }
    }//GEN-LAST:event_tfKMMGGKeyPressed

    private void tfKMTCTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKMTCTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKMTGBD.requestFocus();
        }
    }//GEN-LAST:event_tfKMTCTKeyPressed

    private void tfKMTGBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKMTGBDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKMTGKT.requestFocus();
        }
    }//GEN-LAST:event_tfKMTGBDKeyPressed

    private void tfKMTGKTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKMTGKTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKMG.requestFocus();
        }
    }//GEN-LAST:event_tfKMTGKTKeyPressed

    private void tfDMKMSHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDMKMSHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDMKMMKM.requestFocus();
        }
    }//GEN-LAST:event_tfDMKMSHDKeyPressed

    private void tfDMKMMKMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDMKMMKMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDMKMNKM.requestFocus();
        }
    }//GEN-LAST:event_tfDMKMMKMKeyPressed

    private void tfDMKMNKMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDMKMNKMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfDMKMGG.requestFocus();
        }
    }//GEN-LAST:event_tfDMKMNKMKeyPressed

    private void tfSDDVDGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSDDVDGKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(tfSDDVDG.getText().length()>0){
                lbTT.setText((Integer.valueOf(tfSDDVDG.getText())*Integer.valueOf(lbSL.getText()))+"");
            }
        }
        
        
    }//GEN-LAST:event_tfSDDVDGKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCTKMTim;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btClearDV;
    private javax.swing.JButton btDMKMSua;
    private javax.swing.JButton btDMKMThem;
    private javax.swing.JButton btDMKMxoa;
    private javax.swing.JButton btDVTim;
    private javax.swing.JButton btDVXoa;
    private javax.swing.JButton btKMSua;
    private javax.swing.JButton btKMThem;
    private javax.swing.JButton btKMXoa;
    private javax.swing.JButton btSDDVThem;
    private javax.swing.JButton btSDDVTim;
    private javax.swing.JButton btSDDVXoa;
    private javax.swing.JButton btSuaDV;
    private javax.swing.JButton btThenDV;
    private javax.swing.JButton btXoaSDDV;
    private javax.swing.JComboBox<String> cbDMKMLKM;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbCong;
    private javax.swing.JLabel lbDMKMNgay;
    private javax.swing.JLabel lbSL;
    private javax.swing.JLabel lbTT;
    private javax.swing.JLabel lbTru;
    private javax.swing.JTextArea taDMKMND;
    private javax.swing.JTable tbDMKM;
    private javax.swing.JTable tbDV;
    private javax.swing.JTable tbKM;
    private javax.swing.JTabbedPane tbPane;
    private javax.swing.JTable tbSDDV;
    private javax.swing.JTextField tfDMKMGG;
    private javax.swing.JTextField tfDMKMMKM;
    private javax.swing.JTextField tfDMKMNKM;
    private javax.swing.JTextField tfDMKMSHD;
    private javax.swing.JTextField tfDVGDV;
    private javax.swing.JTextField tfDVMDV;
    private javax.swing.JTextField tfDVMMH;
    private javax.swing.JTextField tfDVTDV;
    private javax.swing.JTextField tfKMG;
    private javax.swing.JTextField tfKMMGG;
    private javax.swing.JTextField tfKMTCT;
    private javax.swing.JTextField tfKMTGBD;
    private javax.swing.JTextField tfKMTGKT;
    private javax.swing.JTextField tfSDDVDG;
    private javax.swing.JTextField tfSDDVMDV;
    private javax.swing.JTextField tfSDDVSHD;
    // End of variables declaration//GEN-END:variables
}
