/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.io.IOException;
import java.sql.Array;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.HoaDonBUS;
import qlks.BUS.HopDongThuePhongBUS;
import qlks.BUS.PhongBUS;
import qlks.DTO.HoaDon;
import qlks.DTO.HoaDonDTO;
import qlks.DTO.HopDongThuePhong;
import qlks.DTO.HopDongThuePhongDTO;
import qlks.DTO.Phong;
import qlks.DTO.PhongDTO;
import qlks.DTO.ReadWriteExcelFile;
import qlks.Model.ModelHoaDon;
import qlks.Model.ModelPhong;
import qlks.Model.ModelHopDongThuePhong;

/**
 *
 * @author Nguyen Tien Dung
 */
public class hoadon extends javax.swing.JPanel {
    private HoaDonDTO hdDTO = new HoaDonDTO();
    private HoaDonBUS hdBUS = new HoaDonBUS();
    HoaDon hd;
    DefaultTableModel model;
    ModelHoaDon hdMD;
    int row = -1;
    
    //Danh sach tam
    ArrayList<HoaDon> dshdt = null;
    /**
     * Creates new form hoadon
     */
    public hoadon() {
        initComponents();
        
        
        hdMD = new ModelHoaDon(hdDTO.docDanhSachHoaDon());
        model = hdMD.getModel();
        tbHD.setModel(model);
        tfHDNTT.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        tfHDMNV.setText(MENUFORM.maNhanVien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfHDSHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHDSoHopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfHDMNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfHDGT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfHDTDV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfHDTKM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfHDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfHDTT = new javax.swing.JTextField();
        btHDThem = new javax.swing.JButton();
        btHDSua = new javax.swing.JButton();
        btHDXoa = new javax.swing.JButton();
        btHDClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfHDNTT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 0, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "QUẢN LÝ HÓA ĐƠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 255, 0))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Thông tin hóa đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel1.setText("Số hóa đơn");

        tfHDSHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHDSHDActionPerformed(evt);
            }
        });
        tfHDSHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDSHDKeyPressed(evt);
            }
        });

        jLabel2.setText("Số hợp đồng");

        tfHDSoHopDong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDSoHopDongKeyPressed(evt);
            }
        });

        jLabel3.setText("Mã nhân viên");

        tfHDMNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDMNVKeyPressed(evt);
            }
        });

        jLabel4.setText("Giá phòng ");

        tfHDGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHDGTActionPerformed(evt);
            }
        });
        tfHDGT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDGTKeyPressed(evt);
            }
        });

        jLabel5.setText("Tiền dịch vụ");

        tfHDTDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDTDVKeyPressed(evt);
            }
        });

        jLabel6.setText("Tiền khuyến mãi");

        tfHDTKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDTKMKeyPressed(evt);
            }
        });

        jLabel7.setText("Thuế ");

        tfHDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDTKeyPressed(evt);
            }
        });

        jLabel8.setText("Tổng tiền");

        btHDThem.setBackground(new java.awt.Color(0, 153, 153));
        btHDThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btHDThem.setText("Thêm");
        btHDThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDThemActionPerformed(evt);
            }
        });

        btHDSua.setBackground(new java.awt.Color(0, 153, 153));
        btHDSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btHDSua.setText("Sửa");
        btHDSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDSuaActionPerformed(evt);
            }
        });

        btHDXoa.setBackground(new java.awt.Color(0, 153, 153));
        btHDXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btHDXoa.setText("Xóa");
        btHDXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDXoaActionPerformed(evt);
            }
        });

        btHDClear.setBackground(new java.awt.Color(0, 153, 153));
        btHDClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btHDClear.setText("Clear");
        btHDClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDClearActionPerformed(evt);
            }
        });

        jLabel10.setText("Ngày thanh toán ");

        tfHDNTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHDNTTKeyPressed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btHDThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btHDSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfHDSHD)
                            .addComponent(tfHDGT)
                            .addComponent(tfHDTDV)
                            .addComponent(tfHDTKM)
                            .addComponent(tfHDT)
                            .addComponent(tfHDTT)
                            .addComponent(tfHDSoHopDong)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfHDNTT)
                                    .addComponent(tfHDMNV))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btHDXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btHDClear)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfHDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHDSoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHDMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfHDNTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHDGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfHDTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfHDTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfHDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHDTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHDThem)
                    .addComponent(btHDSua))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHDXoa)
                    .addComponent(btHDClear))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách hóa đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setToolTipText("");

        tbHD.setBackground(new java.awt.Color(255, 255, 204));
        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã hợp đồng", "Mã KH", "Ngày", "Tiền phòng", "Tiền DV", "Tiền KM", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbHDMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfHDSHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHDSHDActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_tfHDSHDActionPerformed

    private void tfHDGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHDGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHDGTActionPerformed

    private void tbHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMousePressed
        row = tbHD.getSelectedRow();
        
        if(dshdt==null){
            hd = hdDTO.getHoaDon(row);
            
            tfHDSHD.setText(hd.getSoHoaDon());
            tfHDSoHopDong.setText(hd.getSoHopDongThuePhong());
            tfHDMNV.setText(hd.getMaNhanVien());
            tfHDNTT.setText(hd.getNgayThanhToan());
            tfHDGT.setText(hd.getTienThuePhong()+"");
            tfHDTDV.setText(hd.getTienDichVu()+"");
            tfHDTKM.setText(hd.getTienKhuyenMai()+"");
            tfHDT.setText(hd.getThue()+"");
            tfHDTT.setText(hd.getTongTien()+"");
        }else{
            hd = dshdt.get(row);
            
            tfHDSHD.setText(hd.getSoHoaDon());
            tfHDSoHopDong.setText(hd.getSoHopDongThuePhong());
            tfHDMNV.setText(hd.getMaNhanVien());
            tfHDNTT.setText(hd.getNgayThanhToan());
            tfHDGT.setText(hd.getTienThuePhong()+"");
            tfHDTDV.setText(hd.getTienDichVu()+"");
            tfHDTKM.setText(hd.getTienKhuyenMai()+"");
            tfHDT.setText(hd.getThue()+"");
            tfHDTT.setText(hd.getTongTien()+"");
        }
    }//GEN-LAST:event_tbHDMousePressed

    private void btHDThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDThemActionPerformed
        if(tfHDSHD.getText().length()>0&&tfHDSoHopDong.getText().length()>0&&tfHDMNV.getText().length()>0&&
                tfHDNTT.getText().length()>0&&tfHDGT.getText().length()>0&&tfHDTDV.getText().length()>0&&
                tfHDTKM.getText().length()>0&&tfHDT.getText().length()>0&&tfHDTT.getText().length()>0){
            hd = new HoaDon();
            
            if(hd.setSoHoaDonKT(tfHDSHD.getText()) == false){
                return;
            }
            hd.setSoHopDongThuePhong(tfHDSoHopDong.getText());
            hd.setMaNhanVien(tfHDMNV.getText());
            String ngayThue = "";
            for(HopDongThuePhong hdtp: new HopDongThuePhongDTO().docDanhSachHopDongThuePhong()){
                if(tfHDSoHopDong.getText().compareTo(hdtp.getSoHopDongThuePhong())==0){
                    ngayThue = hdtp.getNgayThue();
                }
            }
            if(hd.setNgayThanhToanKT(tfHDNTT.getText(),ngayThue) == false){
                return;
            }
            if(hd.setTienThuePhong(tfHDGT.getText()) == false){
                return;
            }
            if(hd.setTienDichVu(tfHDTDV.getText()) == false){
                return;
            }
            if(hd.setTienKhuyenMai(tfHDTKM.getText()) == false){
                return;
            }
            if(hd.setThue(tfHDT.getText()) == false){
                return;
            }
            if(hd.setTongTien(tfHDTT.getText()) == false){
                return;
            }
            
            if(hdBUS.themHoaDon(hdDTO, hd)){
                
                HopDongThuePhongDTO hdtpDTO = phong.hdpDTO;
                HopDongThuePhong hdtp = null;
                for(HopDongThuePhong hdtpt: hdtpDTO.docDanhSachHopDongThuePhong()){
                    if(hd.getSoHopDongThuePhong().compareTo(hdtpt.getSoHopDongThuePhong())==0){
                        hdtp = hdtpt;
                        break;
                    }
                }
                
                hdtp.setTrangThai("Đã thanh toán");
                HopDongThuePhongBUS hdtpBUS = new HopDongThuePhongBUS();
                hdtpBUS.suaHopDongThuePhongTuHoaDon(hdtp);
                hdtpDTO.suaHopDongThuePhong(hdtp);
                
                PhongDTO pDTO = phong.pDTO;
                Phong p = null;
                for(Phong pt: pDTO.docDanhSachPhong()){
                    if(pt.getMaPhong().compareTo(hdtp.getMaPhong())==0){
                        p = pt;
                        break;
                    }
                }
                p.setTinhTrang("Trống");
                PhongBUS pBUS = new PhongBUS();
                pBUS.suaPhongTuHoaDon(p);
                pDTO.suaPhong(p);
                
                tbHD.setModel(new ModelHoaDon(hdDTO.docDanhSachHoaDon()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btHDThemActionPerformed

    private void btHDSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDSuaActionPerformed
        if(tfHDSHD.getText().length()>0&&tfHDSoHopDong.getText().length()>0&&tfHDMNV.getText().length()>0&&
                tfHDNTT.getText().length()>0&&tfHDGT.getText().length()>0&&tfHDTDV.getText().length()>0&&
                tfHDTKM.getText().length()>0&&tfHDT.getText().length()>0&&tfHDTT.getText().length()>0){
            hd = new HoaDon();
            
            if(hd.setSoHoaDonKT(tfHDSHD.getText()) == false){
                return;
            }
            hd.setSoHopDongThuePhong(tfHDSoHopDong.getText());
            hd.setMaNhanVien(tfHDMNV.getText());
            String ngayThue = "";
            for(HopDongThuePhong hdtp: new HopDongThuePhongDTO().docDanhSachHopDongThuePhong()){
                if(tfHDSoHopDong.getText().compareTo(hdtp.getSoHopDongThuePhong())==0){
                    ngayThue = hdtp.getNgayThue();
                }
            }
            if(hd.setNgayThanhToanKT(tfHDNTT.getText(),ngayThue) == false){
                return;
            }
            if(hd.setTienThuePhong(tfHDGT.getText()) == false){
                return;
            }
            if(hd.setTienDichVu(tfHDTDV.getText()) == false){
                return;
            }
            if(hd.setTienKhuyenMai(tfHDTKM.getText()) == false){
                return;
            }
            if(hd.setThue(tfHDT.getText()) == false){
                return;
            }
            if(hd.setTongTien(tfHDTT.getText()) == false){
                return;
            }
            
            if(hdBUS.suaHoaDon(hdDTO, hd)){
                tbHD.setModel(new ModelHoaDon(hdDTO.docDanhSachHoaDon()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btHDSuaActionPerformed

    private void btHDClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDClearActionPerformed
        tfHDSHD.setText("");
        tfHDSoHopDong.setText("");
        tfHDMNV.setText("");
        tfHDNTT.setText("");
        tfHDGT.setText("");
        tfHDTDV.setText("");
        tfHDTKM.setText("");
        tfHDT.setText("");
        tfHDTT.setText("");
        
        tbHD.setModel(new ModelHoaDon(hdDTO.docDanhSachHoaDon()).getModel());
    }//GEN-LAST:event_btHDClearActionPerformed

    private void btHDXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDXoaActionPerformed
        if(tfHDSHD.getText().length()>0){
            hd = new HoaDon();
            if(hd.setSoHoaDonKT(tfHDSHD.getText()) == false){
                return;
            }
            if(hdBUS.xoaHoaDon(hdDTO, hd)){
                model = new ModelHoaDon(hdDTO.docDanhSachHoaDon()).getModel();
                tbHD.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số hóa đơn");
        }
    }//GEN-LAST:event_btHDXoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tfHDMNV.setText(MENUFORM.maNhanVien);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tfHDNTT.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfHDSHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDSHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDSoHopDong.requestFocus();
        }
    }//GEN-LAST:event_tfHDSHDKeyPressed

    private void tfHDSoHopDongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDSoHopDongKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDMNV.requestFocus();
        }
    }//GEN-LAST:event_tfHDSoHopDongKeyPressed

    private void tfHDMNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDMNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDNTT.requestFocus();
        }
    }//GEN-LAST:event_tfHDMNVKeyPressed

    private void tfHDNTTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDNTTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDGT.requestFocus();
        }
    }//GEN-LAST:event_tfHDNTTKeyPressed

    private void tfHDGTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDGTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDTDV.requestFocus();
        }
    }//GEN-LAST:event_tfHDGTKeyPressed

    private void tfHDTDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDTDVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDTKM.requestFocus();
        }
    }//GEN-LAST:event_tfHDTDVKeyPressed

    private void tfHDTKMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDTKMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDT.requestFocus();
        }
    }//GEN-LAST:event_tfHDTKMKeyPressed

    private void tfHDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHDTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfHDTT.requestFocus();
        }
    }//GEN-LAST:event_tfHDTKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int tienPhong = 0;
        int tienDichVu = 0;
        int tienKhuyenMai = 0;
        int thue = 0;
        int tongTien = 0;
        try{
            tienPhong = Integer.parseInt(tfHDGT.getText());
        }catch(Exception e){
            tienPhong = -1;
        }
        try{
            tienDichVu = Integer.parseInt(tfHDTDV.getText());
        }catch(Exception e){
            tienDichVu = -1;
        }
        try{
            tienKhuyenMai = Integer.parseInt(tfHDTKM.getText());
        }catch(Exception e){
            tienKhuyenMai = -1;
        }
        try{
            thue = Integer.parseInt(tfHDT.getText());
        }catch(Exception e){
            thue = -1;
        }
        try{
            tongTien = Integer.parseInt(tfHDTT.getText());
        }catch(Exception e){
            tongTien = -1;
        }
        
        hd = new HoaDon(); 
        hd.setSoHoaDon(tfHDSHD.getText());
        hd.setSoHopDongThuePhong(tfHDSoHopDong.getText());
        hd.setMaNhanVien(tfHDMNV.getText());
        hd.setNgayThanhToan(tfHDNTT.getText());
        hd.setTienThuePhong(tienPhong);
        hd.setTienDichVu(tienDichVu);
        hd.setTienKhuyenMai(tienKhuyenMai);
        hd.setThue(thue);
        hd.setTongTien(tongTien);
        
        model = new ModelHoaDon(hdDTO.timHoaDon(hd)).getModel();
        tbHD.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHDClear;
    private javax.swing.JButton btHDSua;
    private javax.swing.JButton btHDThem;
    private javax.swing.JButton btHDXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHD;
    private javax.swing.JTextField tfHDGT;
    private javax.swing.JTextField tfHDMNV;
    private javax.swing.JTextField tfHDNTT;
    private javax.swing.JTextField tfHDSHD;
    private javax.swing.JTextField tfHDSoHopDong;
    private javax.swing.JTextField tfHDT;
    private javax.swing.JTextField tfHDTDV;
    private javax.swing.JTextField tfHDTKM;
    private javax.swing.JTextField tfHDTT;
    // End of variables declaration//GEN-END:variables
}
