/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.KhachHangBUS;
import qlks.DTO.KhachHang;
import qlks.DTO.KhachHangDTO;
import static qlks.GUI.MENUFORM.jPanelChane;
import static qlks.GUI.MENUFORM.jchild;
import qlks.Model.ModelKhachHang;

/**
 *
 * @author Nguyen Tien Dung
 */
public class khachhang extends javax.swing.JPanel {
    private KhachHangDTO khDTO = new KhachHangDTO();
    private KhachHangBUS khBUS = new KhachHangBUS();
    KhachHang kh;
    DefaultTableModel model;
    ModelKhachHang khMD;
    int row = -1;
    
    boolean gt = false;
    /**
     * Creates new form khachhang
     */
    public khachhang() {
        initComponents();
        
        model = new ModelKhachHang(khDTO.docDanhSachKhachHang()).getModel();
        tbKH.setModel(model);
        
        btKHChon.setEnabled(false);
        if(MENUFORM.khMaKhachHang){
            btKHChon.setEnabled(true);
            MENUFORM.khMaKhachHang = false;
        }
        
        tfKHMKH.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfKHMKH = new javax.swing.JTextField();
        tfKHH = new javax.swing.JTextField();
        tfKHDC = new javax.swing.JTextField();
        tfKHCMND = new javax.swing.JTextField();
        tfKHSDT = new javax.swing.JTextField();
        btKHThem = new javax.swing.JButton();
        btKHTim = new javax.swing.JButton();
        btKHXoa = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tfKHT = new javax.swing.JTextField();
        btKHSua = new javax.swing.JButton();
        rdKHNam = new javax.swing.JRadioButton();
        rdKHNu = new javax.swing.JRadioButton();
        btKHClear = new javax.swing.JButton();
        btKHChon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKH = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 0, 102));

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)), "QUẢN LÝ KHÁCH HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 255, 0))); // NOI18N

        jPanel15.setBackground(new java.awt.Color(204, 153, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel31.setText("Mã Khách Hàng");

        jLabel32.setText("Họ");

        jLabel33.setText("CMND");

        jLabel34.setText("Giới Tính");

        jLabel35.setText("Số Điện Thoại");

        tfKHMKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMKHActionPerformed(evt);
            }
        });
        tfKHMKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKHMKHKeyPressed(evt);
            }
        });

        tfKHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHActionPerformed(evt);
            }
        });
        tfKHH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKHHKeyPressed(evt);
            }
        });

        tfKHDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKHDCKeyPressed(evt);
            }
        });

        tfKHCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKHCMNDKeyPressed(evt);
            }
        });

        tfKHSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSDTActionPerformed(evt);
            }
        });

        btKHThem.setBackground(new java.awt.Color(0, 153, 153));
        btKHThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btKHThem.setText("Thêm");
        btKHThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btKHTim.setBackground(new java.awt.Color(0, 153, 153));
        btKHTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        btKHTim.setText("Tìm");
        btKHTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        btKHXoa.setBackground(new java.awt.Color(0, 153, 153));
        btKHXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btKHXoa.setText("Xóa");
        btKHXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        jLabel36.setText("Địa chỉ");
        jLabel36.setToolTipText("");

        jLabel37.setText("Tên");

        tfKHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTActionPerformed(evt);
            }
        });
        tfKHT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKHTKeyPressed(evt);
            }
        });

        btKHSua.setBackground(new java.awt.Color(0, 153, 153));
        btKHSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btKHSua.setText("Sửa");
        btKHSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        rdKHNam.setBackground(new java.awt.Color(204, 153, 255));
        rdKHNam.setText("Nam");
        rdKHNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDNamActionPerformed(evt);
            }
        });

        rdKHNu.setBackground(new java.awt.Color(204, 153, 255));
        rdKHNu.setText("Nữ");
        rdKHNu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                RDNuMouseDragged(evt);
            }
        });
        rdKHNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDNuActionPerformed(evt);
            }
        });

        btKHClear.setBackground(new java.awt.Color(0, 153, 153));
        btKHClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btKHClear.setText("Clear");
        btKHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btKHChon.setBackground(new java.awt.Color(0, 153, 153));
        btKHChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/tick.png"))); // NOI18N
        btKHChon.setText("Chọn ");
        btKHChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKHChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btKHThem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btKHSua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel35)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfKHSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfKHDC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                            .addComponent(rdKHNam)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rdKHNu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tfKHT, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfKHCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btKHTim, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btKHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btKHChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btKHXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKHMKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKHH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tfKHMKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfKHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tfKHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(rdKHNam)
                    .addComponent(rdKHNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKHDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfKHCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tfKHSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKHThem)
                    .addComponent(btKHSua))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKHTim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKHXoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKHClear)
                    .addComponent(btKHChon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 51))); // NOI18N
        jPanel1.setToolTipText("");

        tbKH.setBackground(new java.awt.Color(255, 255, 204));
        tbKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "CMND", "Giới tính", "Tuổi", "Số điện thoạii", "Địa chỉ", "Mã phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKH.setToolTipText("");
        tbKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbKHMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbKH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKHMouseClicked

    }//GEN-LAST:event_tbKHMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        tfKHMKH.setEditable(true);
        tfKHMKH.setText("");
        tfKHH.setText("");
        tfKHT.setText("");
        rdKHNam.setSelected(false);
        rdKHNu.setSelected(false);
        gt = false;
        tfKHDC.setText("");
        tfKHCMND.setText("");
        tfKHSDT.setText("");

        model = new ModelKhachHang(khDTO.docDanhSachKhachHang()).getModel();
        tbKH.setModel(model);
    }//GEN-LAST:event_btClearActionPerformed

    private void RDNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDNuActionPerformed
        gt = true;
    }//GEN-LAST:event_RDNuActionPerformed

    private void RDNuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RDNuMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_RDNuMouseDragged

    private void RDNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDNamActionPerformed
        gt = true;
    }//GEN-LAST:event_RDNamActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        if(tfKHMKH.getText().length()>0&&tfKHH.getText().length()>0&&tfKHT.getText().length()>0&&
            tfKHDC.getText().length()>0&&tfKHCMND.getText().length()>0&&tfKHSDT.getText().length()>0&&
            (rdKHNam.isSelected()||rdKHNu.isSelected())){

            kh = new KhachHang();
            kh.setMaKhachHang(tfKHMKH.getText());
            kh.setHo(tfKHH.getText());
            kh.setTen(tfKHT.getText());
            if(rdKHNam.isSelected()){
                kh.setGioiTinh("Nam");
            }else{
                if(rdKHNu.isSelected()){
                    kh.setGioiTinh("Nữ");
                }
            }
            kh.setDiaChi(tfKHDC.getText());
            kh.setCMND(tfKHCMND.getText());
            kh.setDienThoai(tfKHSDT.getText());

            if(khBUS.suaKhachHang(khDTO, kh)){
                Vector vt = new Vector();
                vt.add(kh.getMaKhachHang());
                vt.add(kh.getHo());
                vt.add(kh.getTen());
                vt.add(kh.getGioiTinh());
                vt.add(kh.getDiaChi());
                vt.add(kh.getCMND());
                vt.add(kh.getDienThoai());

                model = new ModelKhachHang(khDTO.docDanhSachKhachHang()).getModel();
                tbKH.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void tfTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if(tfKHMKH.getText().length()>0){
            if(khBUS.xoaKhachHang(khDTO, tfKHMKH.getText())){
                model = new ModelKhachHang(khDTO.docDanhSachKhachHang()).getModel();
                tbKH.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        kh = new KhachHang();
        kh.setMaKhachHang(tfKHMKH.getText());
        kh.setHo(tfKHH.getText());
        kh.setTen(tfKHT.getText());
        if(gt){
            if(rdKHNam.isSelected()){
                kh.setGioiTinh("Nam");
            }else{
                if(rdKHNu.isSelected()){
                    kh.setGioiTinh("Nữ");
                }
            }
        }else{
            kh.setGioiTinh("");
        }

        kh.setDiaChi(tfKHDC.getText());
        kh.setCMND(tfKHCMND.getText());
        kh.setDienThoai(tfKHSDT.getText());

        tbKH.setModel(new ModelKhachHang(khDTO.timKhachHang(kh)).getModel());
    }//GEN-LAST:event_btTimActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if(tfKHMKH.getText().length()>0&&tfKHH.getText().length()>0&&tfKHT.getText().length()>0&&
            tfKHDC.getText().length()>0&&tfKHCMND.getText().length()>0&&tfKHSDT.getText().length()>0&&
            (rdKHNam.isSelected()||rdKHNu.isSelected())){

            kh = new KhachHang();
            kh.setMaKhachHang(tfKHMKH.getText());
            kh.setHo(tfKHH.getText());
            kh.setTen(tfKHT.getText());
            if(rdKHNam.isSelected()){
                kh.setGioiTinh("Nam");
            }else{
                if(rdKHNu.isSelected()){
                    kh.setGioiTinh("Nữ");
                }
            }
            kh.setDiaChi(tfKHDC.getText());
            kh.setCMND(tfKHCMND.getText());
            kh.setDienThoai(tfKHSDT.getText());

            if(khBUS.themKhachHang(khDTO, kh)){
                model = new ModelKhachHang(khDTO.docDanhSachKhachHang()).getModel();
                tbKH.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void tfSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSDTActionPerformed

    private void tfHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHActionPerformed

    private void tfMKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMKHActionPerformed

    private void btKHChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKHChonActionPerformed
        if(tfKHMKH.getText().length()>0){
            boolean timKH = false;
            for(KhachHang kh: khDTO.docDanhSachKhachHang()){
                if(kh.getMaKhachHang().compareTo(tfKHMKH.getText())==0){
                    timKH = true;
                    break;
                }
            }
            if(timKH){
                int chon = JOptionPane.showConfirmDialog(null, "Xác nhận chọn");
                if(chon==JOptionPane.YES_OPTION){
                    MENUFORM.dlMaKhachHang = tfKHMKH.getText();
                    btKHChon.setEnabled(false);
                    MENUFORM.pMaKhachHang = true;
                    MENUFORM.formatButton(3);
                }
            }else{
                int chon = JOptionPane.showConfirmDialog(null, "Khách hàng không tồn tại xác nhận tạo mới");
                if(chon==JOptionPane.YES_OPTION){
                    tfKHMKH.setEditable(false);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng chọn mã khách hàng");
        }
    }//GEN-LAST:event_btKHChonActionPerformed

    private void tbKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKHMousePressed
        row = tbKH.getSelectedRow();

        kh = khDTO.getKhachHang(row);
        tfKHMKH.setText(model.getValueAt(row, 0).toString());
        tfKHH.setText(model.getValueAt(row, 1).toString());
        tfKHT.setText(model.getValueAt(row, 2).toString());
        if(model.getValueAt(row, 3).toString().compareTo("Nam")==0){
            rdKHNam.setSelected(true);
        }else{
            rdKHNu.setSelected(true);
        }
        tfKHDC.setText(model.getValueAt(row, 4).toString());
        tfKHCMND.setText(model.getValueAt(row, 5).toString());
        tfKHSDT.setText(model.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tbKHMousePressed

    private void tfKHMKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKHMKHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKHH.requestFocus();
        }
    }//GEN-LAST:event_tfKHMKHKeyPressed

    private void tfKHHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKHHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKHT.requestFocus();
        }
    }//GEN-LAST:event_tfKHHKeyPressed

    private void tfKHTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKHTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            rdKHNam.setSelected(true);
            tfKHDC.requestFocus();
        }
    }//GEN-LAST:event_tfKHTKeyPressed

    private void tfKHDCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKHDCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKHCMND.requestFocus();
        }
    }//GEN-LAST:event_tfKHDCKeyPressed

    private void tfKHCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKHCMNDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfKHSDT.requestFocus();
        }
    }//GEN-LAST:event_tfKHCMNDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKHChon;
    private javax.swing.JButton btKHClear;
    private javax.swing.JButton btKHSua;
    private javax.swing.JButton btKHThem;
    private javax.swing.JButton btKHTim;
    private javax.swing.JButton btKHXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdKHNam;
    private javax.swing.JRadioButton rdKHNu;
    private javax.swing.JTable tbKH;
    private javax.swing.JTextField tfKHCMND;
    private javax.swing.JTextField tfKHDC;
    private javax.swing.JTextField tfKHH;
    private javax.swing.JTextField tfKHMKH;
    private javax.swing.JTextField tfKHSDT;
    private javax.swing.JTextField tfKHT;
    // End of variables declaration//GEN-END:variables
}
