/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.NhanVienBUS;
import qlks.DTO.NhanVien;
import qlks.DTO.NhanVienDTO;
import qlks.Model.ModelNhanVien;
import qlks.Model.ModelTaiKhoan;

/**
 *
 * @author Nguyen Tien Dung
 */
public class nhanvien extends javax.swing.JPanel {
    private NhanVienDTO nvDTO = new NhanVienDTO();
    private NhanVienBUS nvBUS = new NhanVienBUS();
    NhanVien nv;
    DefaultTableModel model;
    int row = -1;
    
    DefaultTableModel modelQL;
    int rowQL = -1;
    /**
     * Creates new form nhanvien
     */
    public nhanvien() {
        initComponents();
        
        hienThiTaiKhoan();
        
        tfQLNV.requestFocus();
    }
    
    public void hienThiTaiKhoan(){
        modelQL = new ModelTaiKhoan(nvDTO.docDanhSachNhanVien()).getModel();
        tbQLTK.setModel(modelQL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.ButtonGroup();
        tpQLNV = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfQLNV = new javax.swing.JTextField();
        tfQLTK = new javax.swing.JTextField();
        tfQLMK = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btQLSua = new javax.swing.JButton();
        btQLClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbQLTK = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMNV = new javax.swing.JTextField();
        tfH = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfDC = new javax.swing.JTextField();
        tfCMND = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfT = new javax.swing.JTextField();
        tfNS = new javax.swing.JTextField();
        tfNVL = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        cbNV = new javax.swing.JComboBox<>();
        btLoc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQLNV = new javax.swing.JTable();

        tpQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpQLNVMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)), "QUẢN LÝ TÀI KHOẢN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Quản lý tài khoản truy cập", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 51))); // NOI18N

        jLabel11.setText("Nhân viên");

        tfQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQLNVActionPerformed(evt);
            }
        });
        tfQLNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQLNVKeyPressed(evt);
            }
        });

        tfQLTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQLTKKeyPressed(evt);
            }
        });

        jLabel12.setText("Mật khẩu");

        jLabel14.setText("Tài khoản");

        btQLSua.setBackground(new java.awt.Color(0, 153, 153));
        btQLSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btQLSua.setText("Đổi mật khẩu");
        btQLSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLSuaActionPerformed(evt);
            }
        });

        btQLClear.setBackground(new java.awt.Color(0, 153, 153));
        btQLClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btQLClear.setText("Clear");
        btQLClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLClearActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/k1.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/k.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(tfQLMK))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btQLSua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btQLClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQLNV)
                            .addComponent(tfQLTK))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfQLMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQLSua)
                    .addComponent(btQLClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách tài khoản truy cập", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        tbQLTK.setBackground(new java.awt.Color(255, 255, 204));
        tbQLTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên nhân viên", "Tên đăng nhập", "Mật khẩu", "Quyền truy cập"
            }
        ));
        tbQLTK.setToolTipText("");
        tbQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbQLTKMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbQLTK);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpQLNV.addTab("Quản lí tài khoản", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "QUẢN LÝ NHÂN VIÊN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 255, 0))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel2.setText("Mã nhân viên ");

        jLabel3.setText("Họ");

        jLabel4.setText("Ngày sinh ");

        jLabel5.setText("Giới Tính");

        jLabel6.setText("Địa chỉ");

        jLabel7.setText("CMND");

        jLabel8.setText("Số điện thoại");

        tfMNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMNVKeyPressed(evt);
            }
        });

        tfH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHActionPerformed(evt);
            }
        });
        tfH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHKeyPressed(evt);
            }
        });

        tfSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSDTKeyPressed(evt);
            }
        });

        tfDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDCKeyPressed(evt);
            }
        });

        tfCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCMNDKeyPressed(evt);
            }
        });

        them.setBackground(new java.awt.Color(0, 153, 153));
        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setBackground(new java.awt.Color(0, 153, 153));
        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        xoa.setBackground(new java.awt.Color(0, 153, 153));
        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        btClear.setBackground(new java.awt.Color(0, 153, 153));
        btClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngày vào làm");

        jLabel10.setText("Lương");

        jLabel16.setText("Tên");

        tfT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTActionPerformed(evt);
            }
        });
        tfT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTKeyPressed(evt);
            }
        });

        tfNS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNSKeyPressed(evt);
            }
        });

        tfNVL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNVLKeyPressed(evt);
            }
        });

        btGroup.add(rdNam);
        rdNam.setText("Nam ");

        btGroup.add(rdNu);
        rdNu.setText("Nữ ");

        cbNV.setBackground(new java.awt.Color(0, 153, 153));
        cbNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chinh xac", "Theo muc" }));

        btLoc.setBackground(new java.awt.Color(0, 153, 153));
        btLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/filter.png"))); // NOI18N
        btLoc.setText("Lọc");
        btLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(tfMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNS, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNVL, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdNam)
                        .addComponent(rdNu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tfNVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(xoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sua)
                    .addComponent(btClear))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbNV))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh Sách Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        tbQLNV.setBackground(new java.awt.Color(255, 255, 204));
        tbQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ nhân viên", "Tên nhân viên", "Chức vụ", "Lương", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại", "Ngày vào làm"
            }
        ));
        tbQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQLNVMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbQLNVMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbQLNV);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpQLNV.addTab("Quản lí nhân viên", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpQLNV)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpQLNV, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQLNVActionPerformed

    private void btQLSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLSuaActionPerformed
        if(tfQLTK.getText().length()>0 && tfQLMK.getText().length()>0){
            if(nvBUS.doiMatKhauNhanVien(tfQLTK.getText(), tfQLMK.getText())){
                nvDTO.doiMatKhau(tfQLTK.getText(), tfQLMK.getText());
                modelQL = new ModelTaiKhoan(nvDTO.docDanhSachNhanVien()).getModel();
                tbQLTK.setModel(modelQL);
            }
        }
    }//GEN-LAST:event_btQLSuaActionPerformed

    private void btQLClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLClearActionPerformed
        tfQLNV.setText("");
        tfQLTK.setText("");
        tfQLMK.setText("");
        
        modelQL = new ModelTaiKhoan(nvDTO.docDanhSachNhanVien()).getModel();
        tbQLTK.setModel(modelQL);
    }//GEN-LAST:event_btQLClearActionPerformed

    private void tfHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed

        //Kiem tra cac textField
        if(tfMNV.getText().length()>0&&tfH.getText().length()>0&&tfT.getText().length()>0&&
            tfNS.getText().length()>0&&(rdNam.isSelected()||rdNu.isSelected())&&tfDC.getText().length()>0&&
            tfCMND.getText().length()>0&&tfSDT.getText().length()>0&&
            tfNVL.getText().length()>0&&tfL.getText().length()>0){
            //Tao moi nhan vien
            nv = new NhanVien();
            nv.setMaNhanVien(tfMNV.getText());
            nv.setHo(tfH.getText());
            nv.setTen(tfT.getText());
            if(nv.setNgaySinhKT(tfNS.getText()) == false){
                return;
            }
            if(rdNam.isSelected()){
                nv.setGioiTinh("Nam");
            }else{
                nv.setGioiTinh("Nữ");
            }
            nv.setDiaChi(tfDC.getText());
            nv.setCMMD(tfCMND.getText());
            nv.setDienThoai(tfSDT.getText());
            if(nv.setNgayVaoLamKT(tfNVL.getText()) == false){
                return;
            }
            if(nv.setLuongThang(tfL.getText()) == false){
                return;
            }
            nv.setMatKhau("123");
            nv.setXoa(false);

            //Them nhan vien thong qua BUS
            if(nvBUS.themNhanVien(nvDTO, nv)){
                model = new ModelNhanVien(nvDTO.docDanhSachNhanVien()).getModel();
                tbQLNV.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_themActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        if(tfMNV.getText().length()>0&&tfH.getText().length()>0&&tfT.getText().length()>0&&
            tfNS.getText().length()>0&&(rdNam.isSelected()||rdNu.isSelected())&&tfDC.getText().length()>0&&
            tfCMND.getText().length()>0&&tfSDT.getText().length()>0&&
            tfNVL.getText().length()>0&&tfL.getText().length()>0){
            //Tao moi nhan vien
            nv = new NhanVien();
            nv.setMaNhanVien(tfMNV.getText());
            nv.setHo(tfH.getText());
            nv.setTen(tfT.getText());
            if(nv.setNgaySinhKT(tfNS.getText()) == false){
                return;
            }
            if(rdNam.isSelected()){
                nv.setGioiTinh("Nam");
            }else{
                nv.setGioiTinh("Nữ");
            }
            nv.setDiaChi(tfDC.getText());
            nv.setCMMD(tfCMND.getText());
            nv.setDienThoai(tfSDT.getText());
            if(nv.setNgayVaoLamKT(tfNVL.getText()) == false){
                return;
            }
            if(nv.setLuongThang(tfL.getText()) == false){
                return;
            }

            if(nvBUS.suaNhanVien(nvDTO, nv)){
                model = new ModelNhanVien(nvDTO.docDanhSachNhanVien()).getModel();
                tbQLNV.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_suaActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        if(tfMNV.getText().length()>0){
            if(nvBUS.xoaNhanVien(nvDTO ,tfMNV.getText())){
                model = new ModelNhanVien(nvDTO.docDanhSachNhanVien()).getModel();
                tbQLNV.setModel(model);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã nhân viên cần xóa");
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        tfMNV.setText("");
        tfH.setText("");
        tfT.setText("");
        tfNS.setText("");
        rdNam.setSelected(false);
        rdNu.setSelected(false);
        tfDC.setText("");
        tfCMND.setText("");
        tfSDT.setText("");
        tfNVL.setText("");
        tfL.setText("");

        model = new ModelNhanVien(nvDTO.docDanhSachNhanVien()).getModel();
        tbQLNV.setModel(model);
    }//GEN-LAST:event_btClearActionPerformed

    private void tfTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTActionPerformed

    private void tbQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQLNVMouseClicked

    }//GEN-LAST:event_tbQLNVMouseClicked

    private void tpQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpQLNVMouseClicked
        model = new ModelNhanVien(nvDTO.docDanhSachNhanVien()).getModel();
        tbQLNV.setModel(model);
    }//GEN-LAST:event_tpQLNVMouseClicked

    private void tbQLNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQLNVMousePressed
        //vi tri click chuot vao table
        row = tbQLNV.getSelectedRow();

        nv = nvDTO.getNhanVien(row);
        tfMNV.setText(model.getValueAt(row, 0).toString());
        tfH.setText(model.getValueAt(row, 1).toString());
        tfT.setText(model.getValueAt(row, 2).toString());
        tfNS.setText(model.getValueAt(row, 3).toString());
        if(model.getValueAt(row, 4).toString().compareTo("Nam")==0){
            rdNam.setSelected(true);
        }else{
            rdNu.setSelected(true);
        }
        tfDC.setText(model.getValueAt(row, 5).toString());
        tfCMND.setText(model.getValueAt(row, 6).toString());
        tfSDT.setText(model.getValueAt(row, 7).toString());
        tfNVL.setText(model.getValueAt(row, 8).toString());
        tfL.setText(String.valueOf(model.getValueAt(row, 9).toString()));
    }//GEN-LAST:event_tbQLNVMousePressed

    private void btLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocActionPerformed
        int luong = 0;
        try{
            luong = Integer.parseInt(tfL.getText());
        }catch(Exception e){
            luong = -1;
        }
        
        nv = new NhanVien();
        nv.setMaNhanVien(tfMNV.getText());
        nv.setHo(tfH.getText());
        nv.setTen(tfT.getText());
        nv.setNgaySinh(tfNS.getText());
        if(rdNam.isSelected()){
            nv.setGioiTinh("Nam");
        }else{
            if(rdNu.isSelected()){
                nv.setGioiTinh("Nữ");
            } 
        }
        nv.setDiaChi(tfDC.getText());
        nv.setCMMD(tfCMND.getText());
        nv.setDienThoai(tfSDT.getText());
        nv.setNgayVaoLam(tfNVL.getText());
        nv.setLuongThang(luong);
        ArrayList<NhanVien> dstnv = null;
        if(cbNV.getSelectedIndex()==0){
            dstnv = nvDTO.timNhanVienChichXac(nv);
        }else{
            if(cbNV.getSelectedIndex()==1){
                dstnv = nvDTO.timNhanVienTheoMuc(nv);
            }
        }
        
        if(dstnv.size()>0){
            tbQLNV.setModel(new ModelNhanVien(dstnv).getModel());
        }else{
            JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên");
        }                
    }//GEN-LAST:event_btLocActionPerformed

    private void tbQLTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQLTKMousePressed
        rowQL = tbQLTK.getSelectedRow();
        
        tfQLNV.setText(modelQL.getValueAt(rowQL, 0).toString());
        tfQLTK.setText(modelQL.getValueAt(rowQL, 1).toString());
        tfQLMK.setText(modelQL.getValueAt(rowQL, 2).toString());
    }//GEN-LAST:event_tbQLTKMousePressed

    private void tfQLNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQLNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfQLTK.requestFocus();
        }
    }//GEN-LAST:event_tfQLNVKeyPressed

    private void tfQLTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQLTKKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfQLMK.requestFocus();
        }
    }//GEN-LAST:event_tfQLTKKeyPressed

    private void tfMNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfH.requestFocus();
        }
    }//GEN-LAST:event_tfMNVKeyPressed

    private void tfHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfT.requestFocus();
        }
    }//GEN-LAST:event_tfHKeyPressed

    private void tfTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfNS.requestFocus();
        }
    }//GEN-LAST:event_tfTKeyPressed

    private void tfNSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNSKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            rdNam.setSelected(true);
            tfDC.requestFocus();
        }
    }//GEN-LAST:event_tfNSKeyPressed

    private void tfDCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfCMND.requestFocus();
        }
    }//GEN-LAST:event_tfDCKeyPressed

    private void tfCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCMNDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfSDT.requestFocus();
        }
    }//GEN-LAST:event_tfCMNDKeyPressed

    private void tfSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSDTKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfNVL.requestFocus();
        }
    }//GEN-LAST:event_tfSDTKeyPressed

    private void tfNVLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNVLKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfL.requestFocus();
        }
    }//GEN-LAST:event_tfNVLKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MENUFORM.formatButton(7);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.ButtonGroup btGroup;
    private javax.swing.JButton btLoc;
    private javax.swing.JButton btQLClear;
    private javax.swing.JButton btQLSua;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JButton sua;
    private javax.swing.JTable tbQLNV;
    private javax.swing.JTable tbQLTK;
    private javax.swing.JTextField tfCMND;
    private javax.swing.JTextField tfDC;
    private javax.swing.JTextField tfH;
    private javax.swing.JTextField tfL;
    private javax.swing.JTextField tfMNV;
    private javax.swing.JTextField tfNS;
    private javax.swing.JTextField tfNVL;
    private javax.swing.JTextField tfQLMK;
    private javax.swing.JTextField tfQLNV;
    private javax.swing.JTextField tfQLTK;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfT;
    private javax.swing.JButton them;
    private javax.swing.JTabbedPane tpQLNV;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
