/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.ChiTietNhapHangBUS;
import qlks.BUS.MatHangBUS;
import qlks.BUS.PhieuNhapHangBUS;
import qlks.DTO.ChiTietNhapHang;
import qlks.DTO.ChiTietNhapHangDTO;
import qlks.DTO.MatHang;
import qlks.DTO.MatHangDTO;
import qlks.DTO.PhieuNhapHang;
import qlks.DTO.PhieuNhapHangDTO;
import qlks.Model.ModelChiTietNhapHang;
import qlks.Model.ModelMatHang;
import qlks.Model.ModelPhieuNhapHang;

/**
 *
 * @author Nguyen Tien Dung
 */
public class nhaphang extends javax.swing.JPanel {
    //mat hang
    public static MatHangDTO mhDTO = new MatHangDTO();
    private MatHangBUS mhBUS = new MatHangBUS();
    MatHang mh;
    DefaultTableModel modelmh;
    ModelMatHang mhMD;
    int rowmh = -1;
    
    //chi tiet nhap hang
    static ChiTietNhapHangDTO ctnhDTO = new ChiTietNhapHangDTO();
    private ChiTietNhapHangBUS ctnhBUS = new ChiTietNhapHangBUS();
    ChiTietNhapHang ctnh;
    DefaultTableModel modelctnh;
    ModelChiTietNhapHang ctnhMD;
    int rowctnh = -1;
    
    //phieu nhap hang
    private PhieuNhapHangDTO pnhDTO = new PhieuNhapHangDTO();
    private PhieuNhapHangBUS pnhBUS = new PhieuNhapHangBUS();
    PhieuNhapHang pnh;
    DefaultTableModel modelpnh;
    ModelPhieuNhapHang pnhMD;
    int rowpnh = -1;
    
    //Bien toan cuc
    String maPhieuNhapHang = "";
    
    /**
     * Creates new form nhaphangform
     */
    public nhaphang() {
        initComponents();
        //mat hang
        tfCTNHTT.setEditable(false);
        modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
        tbMH.setModel(modelmh);
        
        
        //chi tiet nhap hang
        modelctnh = new ModelChiTietNhapHang(ctnhDTO.docDanhSachChiTietNhapHang()).getModel();
        tbCTNH.setModel(modelctnh);
        
        //phieu nhap hang
        tfPNHMNV.setText(MENUFORM.maNhanVien);
        tfPNHTT.setText("0");
        tfPNHNNH.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
        tbPNH.setModel(modelpnh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpNhapHang = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMHMHH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMHTH = new javax.swing.JTextField();
        tfMHDG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btMHThem = new javax.swing.JButton();
        btMHXoa = new javax.swing.JButton();
        btMHSua = new javax.swing.JButton();
        btMHClear = new javax.swing.JButton();
        tfMHSL = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMH = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCTNH = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfCTNHMPN = new javax.swing.JTextField();
        tfCTNHMHH = new javax.swing.JTextField();
        tfCTNHDG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfCTNHTT = new javax.swing.JTextField();
        btCTNHThem = new javax.swing.JButton();
        btCTNHSua = new javax.swing.JButton();
        lbCTNHTru = new javax.swing.JLabel();
        lbCTNHSL = new javax.swing.JLabel();
        lbCTNHCong = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfPNHMPNH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPNHMNV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfPNHNNH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfPNHNCC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPNHTT = new javax.swing.JTextField();
        btPNHThem = new javax.swing.JButton();
        btPNHSua = new javax.swing.JButton();
        btPNHXoa = new javax.swing.JButton();
        btPNHClear = new javax.swing.JButton();
        btPNHTim = new javax.swing.JButton();
        btPNHThem1 = new javax.swing.JButton();
        btPNHCham = new javax.swing.JButton();
        btPNHCham1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPNH = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "QUẢN LÝ NHẬP HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 255, 0))); // NOI18N
        jPanel1.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách hàng hóa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel1.setText("Mã hàng hóa");

        tfMHMHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMHMHHActionPerformed(evt);
            }
        });
        tfMHMHH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMHMHHKeyPressed(evt);
            }
        });

        jLabel2.setText("Tên hàng");

        tfMHTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMHTHActionPerformed(evt);
            }
        });
        tfMHTH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMHTHKeyPressed(evt);
            }
        });

        jLabel3.setText("Đơn giá");

        btMHThem.setBackground(new java.awt.Color(0, 153, 153));
        btMHThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btMHThem.setText("Thêm");
        btMHThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMHThemActionPerformed(evt);
            }
        });

        btMHXoa.setBackground(new java.awt.Color(0, 153, 153));
        btMHXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btMHXoa.setText("Xóa");
        btMHXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMHXoaActionPerformed(evt);
            }
        });

        btMHSua.setBackground(new java.awt.Color(0, 153, 153));
        btMHSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btMHSua.setText("Sửa");
        btMHSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMHSuaActionPerformed(evt);
            }
        });

        btMHClear.setBackground(new java.awt.Color(0, 153, 153));
        btMHClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btMHClear.setText("Clear");
        btMHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMHClearActionPerformed(evt);
            }
        });

        tfMHSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMHSLActionPerformed(evt);
            }
        });
        tfMHSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMHSLKeyPressed(evt);
            }
        });

        jLabel14.setText("Số lượng");

        tbMH.setBackground(new java.awt.Color(255, 255, 204));
        tbMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hàng hóa", "Tên hàng", "Đơn giá"
            }
        ));
        tbMH.setSelectionForeground(new java.awt.Color(0, 204, 51));
        tbMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMHMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbMH);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMHDG))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMHThem, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(btMHXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMHClear, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(btMHSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMHMHH)
                            .addComponent(tfMHTH)
                            .addComponent(tfMHSL))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMHMHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMHTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfMHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMHDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMHThem)
                    .addComponent(btMHSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMHXoa)
                    .addComponent(btMHClear)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));

        tbCTNH.setBackground(new java.awt.Color(255, 255, 204));
        tbCTNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCTNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCTNHMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbCTNH);

        jPanel7.setBackground(new java.awt.Color(204, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "CHI TIẾT NHẬP HÀNG ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel15.setText("Mã phiếu nhập");

        jLabel16.setText("Mã hàng hóa");

        jLabel17.setText("Đơn giá");

        tfCTNHMPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCTNHMPNKeyPressed(evt);
            }
        });

        tfCTNHMHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCTNHMHHActionPerformed(evt);
            }
        });
        tfCTNHMHH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCTNHMHHKeyPressed(evt);
            }
        });

        tfCTNHDG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCTNHDGFocusLost(evt);
            }
        });
        tfCTNHDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCTNHDGActionPerformed(evt);
            }
        });
        tfCTNHDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCTNHDGKeyPressed(evt);
            }
        });

        jLabel18.setText("Số lượng");

        jLabel19.setText("Thành tiền");

        btCTNHThem.setBackground(new java.awt.Color(0, 153, 153));
        btCTNHThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btCTNHThem.setText("Thêm");
        btCTNHThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCTNHThemActionPerformed(evt);
            }
        });

        btCTNHSua.setBackground(new java.awt.Color(0, 153, 153));
        btCTNHSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btCTNHSua.setText("Sửa");
        btCTNHSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCTNHSuaActionPerformed(evt);
            }
        });

        lbCTNHTru.setBackground(new java.awt.Color(255, 255, 255));
        lbCTNHTru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCTNHTru.setText("-");
        lbCTNHTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbCTNHTru.setOpaque(true);
        lbCTNHTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCTNHTruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCTNHTruMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCTNHTruMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCTNHTruMouseReleased(evt);
            }
        });

        lbCTNHSL.setBackground(new java.awt.Color(255, 255, 255));
        lbCTNHSL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCTNHSL.setText("0");
        lbCTNHSL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbCTNHSL.setOpaque(true);

        lbCTNHCong.setBackground(new java.awt.Color(255, 255, 255));
        lbCTNHCong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCTNHCong.setText("+");
        lbCTNHCong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbCTNHCong.setOpaque(true);
        lbCTNHCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCTNHCongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCTNHCongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCTNHCongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCTNHCongMouseReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        jButton2.setText("Tìm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCTNHMHH, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(tfCTNHDG)
                    .addComponent(tfCTNHMPN))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCTNHTru, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCTNHSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCTNHCong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfCTNHTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCTNHSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCTNHThem, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfCTNHMPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(btCTNHThem))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCTNHTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCTNHSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCTNHCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCTNHMHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(tfCTNHTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCTNHSua))))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCTNHDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpNhapHang.addTab("Danh sách mặt hàng", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "THÔNG TIN PHIẾU NHẬP HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Thông tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel5.setText("Mã phiếu nhập hàng");

        tfPNHMPNH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPNHMPNHKeyPressed(evt);
            }
        });

        jLabel6.setText("Mã nhân viên");

        tfPNHMNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPNHMNVKeyPressed(evt);
            }
        });

        jLabel8.setText("Ngày nhập hàng");

        tfPNHNNH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPNHNNHKeyPressed(evt);
            }
        });

        jLabel9.setText("Nhà cung cấp ");

        tfPNHNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPNHNCCKeyPressed(evt);
            }
        });

        jLabel10.setText("Tổng tiền");

        btPNHThem.setBackground(new java.awt.Color(0, 153, 153));
        btPNHThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btPNHThem.setText("Thêm");
        btPNHThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHThemActionPerformed(evt);
            }
        });

        btPNHSua.setBackground(new java.awt.Color(0, 153, 153));
        btPNHSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btPNHSua.setText("Sửa");
        btPNHSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHSuaActionPerformed(evt);
            }
        });

        btPNHXoa.setBackground(new java.awt.Color(0, 153, 153));
        btPNHXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btPNHXoa.setText("Xóa");
        btPNHXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHXoaActionPerformed(evt);
            }
        });

        btPNHClear.setBackground(new java.awt.Color(0, 153, 153));
        btPNHClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btPNHClear.setText("Clear");
        btPNHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHClearActionPerformed(evt);
            }
        });

        btPNHTim.setBackground(new java.awt.Color(0, 153, 153));
        btPNHTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        btPNHTim.setText("Tìm");
        btPNHTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHTimActionPerformed(evt);
            }
        });

        btPNHThem1.setBackground(new java.awt.Color(0, 153, 153));
        btPNHThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btPNHThem1.setText("Chi tiết ");
        btPNHThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHThem1ActionPerformed(evt);
            }
        });

        btPNHCham.setText("...");
        btPNHCham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHChamActionPerformed(evt);
            }
        });

        btPNHCham1.setText("...");
        btPNHCham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPNHCham1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPNHNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPNHTT, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPNHMPNH, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(tfPNHMNV)
                                        .addGap(18, 18, 18)
                                        .addComponent(btPNHCham1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(45, 45, 45)
                                .addComponent(tfPNHNNH)
                                .addGap(18, 18, 18)
                                .addComponent(btPNHCham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPNHThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPNHXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPNHThem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btPNHTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPNHClear, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(btPNHSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPNHMPNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPNHMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPNHCham1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfPNHNNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPNHCham, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPNHNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfPNHTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPNHThem)
                    .addComponent(btPNHSua))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPNHClear)
                    .addComponent(btPNHXoa))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPNHTim)
                    .addComponent(btPNHThem1))
                .addGap(55, 55, 55))
        );

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        tbPNH.setBackground(new java.awt.Color(255, 255, 204));
        tbPNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hàng hóa", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền", "Ngày nhập", "Nhà cung cấp"
            }
        ));
        tbPNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbPNHMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbPNH);
        if (tbPNH.getColumnModel().getColumnCount() > 0) {
            tbPNH.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbPNH.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbPNH.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpNhapHang.addTab("Phiếu nhập hàng ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpNhapHang)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfMHTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMHTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMHTHActionPerformed

    private void tfMHMHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMHMHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMHMHHActionPerformed

    private void btPNHXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHXoaActionPerformed
        if(tfPNHMPNH.getText().length()>0){
            pnh = new PhieuNhapHang();
            pnh.setMaPhieuNhapHang(tfPNHMPNH.getText());
            if(pnhBUS.xoaPhieuNhapHang(pnhDTO, pnh)){
                modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
                tbPNH.setModel(modelpnh);
                
                ctnhDTO = new ChiTietNhapHangDTO();
                modelctnh = new ModelChiTietNhapHang(ctnhDTO.docDanhSachChiTietNhapHang()).getModel();
                tbCTNH.setModel(modelctnh);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã phiếu nhập hàng");
        }
    }//GEN-LAST:event_btPNHXoaActionPerformed

    private void btPNHThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHThemActionPerformed
        if(tfPNHMPNH.getText().length()>0&&tfPNHMNV.getText().length()>0&&
                tfPNHNNH.getText().length()>0&&tfPNHNCC.getText().length()>0&&
                tfPNHTT.getText().length()>0){
            
            pnh = new PhieuNhapHang();
            pnh.setMaPhieuNhapHang(tfPNHMPNH.getText());
            pnh.setMaNhanVien(tfPNHMNV.getText());
            if(pnh.setNgayNhapHangKT(tfPNHNNH.getText()) == false){
                return;
            }
            pnh.setNhaCungCap(tfPNHNCC.getText());
            if(pnh.setTongTien(tfPNHTT.getText()) == false){
                return;
            }
            if(pnhBUS.themPhieuNhapHang(pnhDTO, pnh)){
                Vector vt = new Vector();
                vt.add(pnh.getMaPhieuNhapHang());
                vt.add(pnh.getMaNhanVien());
                vt.add(pnh.getNgayNhapHang());
                vt.add(pnh.getNhaCungCap());
                vt.add(pnh.getTongTien()+"");
                
                modelpnh.addRow(vt);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPNHThemActionPerformed

    private void tfMHSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMHSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMHSLActionPerformed

    private void btMHClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMHClearActionPerformed
        tfMHMHH.setText("");
        tfMHTH.setText("");
        tfMHSL.setText("");
        tfMHDG.setText("");
        
        modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
        tbMH.setModel(modelmh);
        
        tfCTNHMPN.setText("");
        tfCTNHMHH.setText("");
        tfCTNHDG.setText("");
        lbCTNHSL.setText("0");
        tfCTNHTT.setText("");
        modelctnh = new ModelChiTietNhapHang(ctnhDTO.docDanhSachChiTietNhapHang()).getModel();
        tbCTNH.setModel(modelctnh);
    }//GEN-LAST:event_btMHClearActionPerformed

    private void tbMHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMHMousePressed
        rowmh = tbMH.getSelectedRow();
        
        tfMHMHH.setText(modelmh.getValueAt(rowmh, 0).toString());
        tfCTNHMHH.setText(modelmh.getValueAt(rowmh, 0).toString());
        tfMHTH.setText(modelmh.getValueAt(rowmh, 1).toString());
        tfMHSL.setText(modelmh.getValueAt(rowmh, 2).toString());
        tfMHDG.setText(modelmh.getValueAt(rowmh, 3).toString());
        
        modelctnh = new ModelChiTietNhapHang(ctnhDTO.getMaHangHoa(modelmh.getValueAt(rowmh, 0).toString())).getModel();
        tbCTNH.setModel(modelctnh);
    }//GEN-LAST:event_tbMHMousePressed

    private void tfCTNHMHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCTNHMHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCTNHMHHActionPerformed

    private void tfCTNHDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCTNHDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCTNHDGActionPerformed

    private void lbCTNHTruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHTruMouseEntered
        lbCTNHTru.setBackground(Color.yellow);
    }//GEN-LAST:event_lbCTNHTruMouseEntered

    private void lbCTNHTruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHTruMouseExited
        lbCTNHTru.setBackground(Color.white);
    }//GEN-LAST:event_lbCTNHTruMouseExited

    private void lbCTNHTruMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHTruMousePressed
        lbCTNHTru.setBackground(Color.RED);
        if(Integer.valueOf(lbCTNHSL.getText())>0){
            lbCTNHSL.setText((Integer.valueOf(lbCTNHSL.getText())-1)+"");
            if(tfCTNHDG.getText().length()>0){
                tfCTNHTT.setText((Integer.valueOf(tfCTNHDG.getText())*Integer.valueOf(lbCTNHSL.getText()))+"");
            }
        }
    }//GEN-LAST:event_lbCTNHTruMousePressed

    private void lbCTNHTruMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHTruMouseReleased
        lbCTNHTru.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbCTNHTruMouseReleased

    private void lbCTNHCongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHCongMouseEntered
        lbCTNHCong.setBackground(Color.yellow);
    }//GEN-LAST:event_lbCTNHCongMouseEntered

    private void lbCTNHCongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHCongMouseExited
        lbCTNHCong.setBackground(Color.white);
    }//GEN-LAST:event_lbCTNHCongMouseExited

    private void lbCTNHCongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHCongMousePressed
        lbCTNHCong.setBackground(Color.RED);
        lbCTNHSL.setText((Integer.valueOf(lbCTNHSL.getText())+1)+"");
        if(tfCTNHDG.getText().length()>0){
            tfCTNHTT.setText((Integer.valueOf(tfCTNHDG.getText())*Integer.valueOf(lbCTNHSL.getText()))+"");
        }
    }//GEN-LAST:event_lbCTNHCongMousePressed

    private void lbCTNHCongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCTNHCongMouseReleased
        lbCTNHCong.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbCTNHCongMouseReleased

    private void btMHThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMHThemActionPerformed
        if(tfMHMHH.getText().length()>0&&tfMHTH.getText().length()>0&&
                tfMHDG.getText().length()>0&&tfMHSL.getText().length()>0){
            
            mh = new MatHang();
            mh.setMaMatHang(tfMHMHH.getText());
            mh.setTenMatHang(tfMHTH.getText());
            if(mh.setSoLuong(tfMHSL.getText()) == false){
                return;
            }
            if(mh.setDonGia(tfMHDG.getText()) == false){
                return;
            }
            
            if(mhBUS.themMatHang(mhDTO, mh)){
                Vector vt = new Vector();
                vt.add(mh.getMaMatHang());
                vt.add(mh.getTenMatHang());
                vt.add(mh.getSoLuong());
                vt.add(mh.getDonGia());
                
                modelmh.addRow(vt);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btMHThemActionPerformed

    private void btMHSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMHSuaActionPerformed
        if(tfMHMHH.getText().length()>0&&tfMHTH.getText().length()>0&&
                tfMHDG.getText().length()>0&&tfMHSL.getText().length()>0){
            
            mh = new MatHang();
            mh.setMaMatHang(tfMHMHH.getText());
            mh.setTenMatHang(tfMHTH.getText());
            if(mh.setSoLuong(tfMHSL.getText()) == false){
                return;
            }
            if(mh.setDonGia(tfMHDG.getText()) == false){
                return;
            }
            
            if(mhBUS.suaMatHang(mhDTO, mh)){
                
                modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
                tbMH.setModel(modelmh);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btMHSuaActionPerformed

    private void tbCTNHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTNHMousePressed
        rowctnh = tbCTNH.getSelectedRow();
        
        tfCTNHMPN.setText(modelctnh.getValueAt(rowctnh, 0).toString());
        tfCTNHMHH.setText(modelctnh.getValueAt(rowctnh, 1).toString());
        tfCTNHDG.setText(modelctnh.getValueAt(rowctnh, 2).toString());
        lbCTNHSL.setText(modelctnh.getValueAt(rowctnh, 3).toString());
        tfCTNHTT.setText(modelctnh.getValueAt(rowctnh, 4).toString());
    }//GEN-LAST:event_tbCTNHMousePressed

    private void btCTNHThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCTNHThemActionPerformed
        if(tfCTNHMPN.getText().length()>0&&tfCTNHMHH.getText().length()>0&&tfCTNHDG.getText().length()>0){
            
            ctnh = new ChiTietNhapHang();
            ctnh.setMaPhieuNhapHang(tfCTNHMPN.getText());
            ctnh.setMaMatHang(tfCTNHMHH.getText());
            if(ctnh.setDonGia(tfCTNHDG.getText()) == false){
                return;
            }
            ctnh.setSoLuong(Integer.valueOf(lbCTNHSL.getText()));
            ctnh.setThanhTien(Integer.valueOf(tfCTNHTT.getText()));
            
            if(ctnhBUS.themChiTietNhapHang(ctnhDTO, ctnh)){
                Vector vt = new Vector();
                vt.add(ctnh.getMaPhieuNhapHang());
                vt.add(ctnh.getMaMatHang());
                vt.add(ctnh.getDonGia());
                vt.add(ctnh.getSoLuong());
                vt.add(ctnh.getThanhTien());
                
                modelctnh.addRow(vt);
                
                //Cap nhat lai so luong mat hang trong kho
                mh = mhDTO.getMaMatHang(ctnh.getMaMatHang());
                mh.setSoLuong(mh.getSoLuong()+ctnh.getSoLuong());
                mhBUS.suaSoLuong(mh);
                
                modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
                tbMH.setModel(modelmh);
                
                
                //Cap nhat lai tong tien o phieu nhap hang
                pnh = pnhDTO.getMaPhieuNhapHang(ctnh.getMaPhieuNhapHang());
                pnh.setTongTien(pnh.getTongTien()+ctnh.getThanhTien());
                pnhBUS.suaTongTien(pnh);
                
                modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
                tbPNH.setModel(modelpnh);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btCTNHThemActionPerformed

    private void tfCTNHDGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCTNHDGFocusLost
        if(tfCTNHDG.getText().length()>0){
            try{
                Integer.parseInt(tfCTNHDG.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Đơn giá là số");
                return;
            }
            tfCTNHTT.setText((Integer.valueOf(lbCTNHSL.getText())*Integer.valueOf(tfCTNHDG.getText()))+"");
        }
        
    }//GEN-LAST:event_tfCTNHDGFocusLost

    private void btCTNHSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCTNHSuaActionPerformed
        if(tfCTNHMPN.getText().length()>0&&tfCTNHMHH.getText().length()>0&&tfCTNHDG.getText().length()>0){
            
            ctnh = new ChiTietNhapHang();
            ctnh.setMaPhieuNhapHang(tfCTNHMPN.getText());
            ctnh.setMaMatHang(tfCTNHMHH.getText());
            if(ctnh.setDonGia(tfCTNHDG.getText()) == false){
                return;
            }
            ctnh.setSoLuong(Integer.valueOf(lbCTNHSL.getText()));
            ctnh.setThanhTien(Integer.valueOf(tfCTNHTT.getText()));
            
            //Giu lai so luong va thanh tien cu
            int soLuong = 0;
            int thanhTien = 0;
            for(ChiTietNhapHang ctnht: ctnhDTO.docDanhSachChiTietNhapHang()){
                if(ctnh.getMaPhieuNhapHang().compareTo(ctnht.getMaPhieuNhapHang())==0 &&
                        ctnh.getMaMatHang().compareTo(ctnht.getMaMatHang())==0){
                    soLuong = ctnht.getSoLuong();
                    thanhTien = ctnht.getThanhTien();
                }
            }
            
            if(ctnhBUS.suaChiTietNhapHang(ctnhDTO, ctnh)){
                
                modelctnh = new ModelChiTietNhapHang(ctnhDTO.docDanhSachChiTietNhapHang()).getModel();
                tbCTNH.setModel(modelctnh);
                
                //Cap nhat lai so luong mat hang trong kho
                mh = mhDTO.getMaMatHang(ctnh.getMaMatHang());
                mh.setSoLuong(mh.getSoLuong()+(ctnh.getSoLuong()-soLuong));
                mhBUS.suaSoLuong(mh);
                
                modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
                tbMH.setModel(modelmh);
                
                
                //Cap nhat lai tong tien o phieu nhap hang
                pnh = pnhDTO.getMaPhieuNhapHang(ctnh.getMaPhieuNhapHang());
                pnh.setTongTien(pnh.getTongTien()+(ctnh.getThanhTien()-thanhTien));
                pnhBUS.suaTongTien(pnh);
                
                modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
                tbPNH.setModel(modelpnh);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btCTNHSuaActionPerformed

    private void tbPNHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPNHMousePressed
        rowpnh = tbPNH.getSelectedRow();
        
        tfPNHMPNH.setText(modelpnh.getValueAt(rowpnh, 0).toString());
        tfPNHMNV.setText(modelpnh.getValueAt(rowpnh, 1).toString());
        tfPNHNNH.setText(modelpnh.getValueAt(rowpnh, 2).toString());
        tfPNHNCC.setText(modelpnh.getValueAt(rowpnh, 3).toString());
        tfPNHTT.setText(modelpnh.getValueAt(rowpnh, 4).toString());
    }//GEN-LAST:event_tbPNHMousePressed

    private void btPNHSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHSuaActionPerformed
        if(tfPNHMPNH.getText().length()>0&&tfPNHMNV.getText().length()>0&&
                tfPNHNNH.getText().length()>0&&tfPNHNCC.getText().length()>0&&
                tfPNHTT.getText().length()>0){
            
            pnh = new PhieuNhapHang();
            pnh.setMaPhieuNhapHang(tfPNHMPNH.getText());
            pnh.setMaNhanVien(tfPNHMNV.getText());
            if(pnh.setNgayNhapHangKT(tfPNHNNH.getText()) == false){
                return;
            }
            pnh.setNhaCungCap(tfPNHNCC.getText());
            if(pnh.setTongTien(tfPNHTT.getText()) == false){
                return;
            }
            if(pnhBUS.suaPhieuNhapHang(pnhDTO, pnh)){
                
                modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
                tbPNH.setModel(modelpnh);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPNHSuaActionPerformed

    private void btPNHThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHThem1ActionPerformed
        if(tfPNHMPNH.getText().length()>0){
            maPhieuNhapHang = tfPNHMPNH.getText();
            
            tpNhapHang.setSelectedIndex(0);
            tfCTNHMPN.setText(maPhieuNhapHang);
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng chọn mã phiêu nhập hàng");
        }
    }//GEN-LAST:event_btPNHThem1ActionPerformed

    private void btPNHClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHClearActionPerformed
        tfPNHMPNH.setText("");
        tfPNHMNV.setText("");
        tfPNHNNH.setText("");
        tfPNHNCC.setText("");
        tfPNHTT.setText("0");
        
        modelpnh = new ModelPhieuNhapHang(pnhDTO.docDanhSachPhieuNhapHang()).getModel();
        tbPNH.setModel(modelpnh);
    }//GEN-LAST:event_btPNHClearActionPerformed

    private void btPNHChamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHChamActionPerformed
        tfPNHNNH.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }//GEN-LAST:event_btPNHChamActionPerformed

    private void btMHXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMHXoaActionPerformed
        if(tfMHMHH.getText().length()>0){
            if(mhBUS.xoaMatHang(mhDTO, tfMHMHH.getText())){
                modelmh = new ModelMatHang(mhDTO.docDanhSachMatHang()).getModel();
                tbMH.setModel(modelmh);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã mặt hàng");
        }
    }//GEN-LAST:event_btMHXoaActionPerformed

    private void btPNHCham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHCham1ActionPerformed
        tfPNHMNV.setText(MENUFORM.maNhanVien);
    }//GEN-LAST:event_btPNHCham1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mh = new MatHang();
        mh.setMaMatHang(tfMHMHH.getText());
        mh.setTenMatHang(tfMHTH.getText());
        if(tfMHSL.getText().length()>0){
            if(mh.setSoLuong(tfMHSL.getText()) == false){
                return;
            }
        }else{
            mh.setSoLuong(-1);
        }
        if(tfMHDG.getText().length()>0){
            if(mh.setDonGia(tfMHDG.getText()) == false){
                return;
            }
        }else{
            mh.setDonGia(-1);
        }
        
        modelmh = new ModelMatHang(mhDTO.timMatHang(mh)).getModel();
        tbMH.setModel(modelmh);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ctnh = new ChiTietNhapHang();
        ctnh.setMaPhieuNhapHang(tfCTNHMPN.getText());
        ctnh.setMaMatHang(tfCTNHMHH.getText());
        if(tfCTNHDG.getText().length()>0){
            if(ctnh.setDonGia(tfCTNHDG.getText()) == false){
                return;
            }
        }else{
            ctnh.setDonGia(-1);
        }
        ctnh.setSoLuong(Integer.valueOf(lbCTNHSL.getText()));
        if(tfCTNHTT.getText().length()>0){
            ctnh.setThanhTien(Integer.valueOf(tfCTNHTT.getText()));
        }else{
            ctnh.setThanhTien(-1);
        }
        
        modelctnh = new ModelChiTietNhapHang(ctnhDTO.timChiTietNhapHang(ctnh)).getModel();
        tbCTNH.setModel(modelctnh);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btPNHTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPNHTimActionPerformed
        pnh = new PhieuNhapHang();
        pnh.setMaPhieuNhapHang(tfPNHMPNH.getText());
        pnh.setMaNhanVien(tfPNHMNV.getText());
        pnh.setNgayNhapHang(tfPNHNNH.getText());
        pnh.setNhaCungCap(tfPNHNCC.getText());
        if(pnh.setTongTien(tfPNHTT.getText()) == false){
            return;
        }
        
        modelpnh = new ModelPhieuNhapHang(pnhDTO.timPhieuNhapHang(pnh)).getModel();
        tbPNH.setModel(modelpnh);
    }//GEN-LAST:event_btPNHTimActionPerformed

    private void tfPNHMPNHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPNHMPNHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPNHMNV.requestFocus();
        }
    }//GEN-LAST:event_tfPNHMPNHKeyPressed

    private void tfPNHMNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPNHMNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPNHNNH.requestFocus();
        }
    }//GEN-LAST:event_tfPNHMNVKeyPressed

    private void tfPNHNNHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPNHNNHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPNHNCC.requestFocus();
        }
    }//GEN-LAST:event_tfPNHNNHKeyPressed

    private void tfPNHNCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPNHNCCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPNHTT.requestFocus();
        }
    }//GEN-LAST:event_tfPNHNCCKeyPressed

    private void tfMHMHHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMHMHHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMHTH.requestFocus();
        }
    }//GEN-LAST:event_tfMHMHHKeyPressed

    private void tfMHTHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMHTHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMHSL.requestFocus();
        }
    }//GEN-LAST:event_tfMHTHKeyPressed

    private void tfMHSLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMHSLKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMHDG.requestFocus();
        }
    }//GEN-LAST:event_tfMHSLKeyPressed

    private void tfCTNHMPNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCTNHMPNKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfCTNHMHH.requestFocus();
        }
    }//GEN-LAST:event_tfCTNHMPNKeyPressed

    private void tfCTNHMHHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCTNHMHHKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfCTNHDG.requestFocus();
        }
    }//GEN-LAST:event_tfCTNHMHHKeyPressed

    private void tfCTNHDGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCTNHDGKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(tfCTNHDG.getText().length()>0){
                tfCTNHTT.setText((Integer.valueOf(lbCTNHSL.getText())*Integer.valueOf(tfCTNHDG.getText()))+"");
            }
        }
    }//GEN-LAST:event_tfCTNHDGKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCTNHSua;
    private javax.swing.JButton btCTNHThem;
    private javax.swing.JButton btMHClear;
    private javax.swing.JButton btMHSua;
    private javax.swing.JButton btMHThem;
    private javax.swing.JButton btMHXoa;
    private javax.swing.JButton btPNHCham;
    private javax.swing.JButton btPNHCham1;
    private javax.swing.JButton btPNHClear;
    private javax.swing.JButton btPNHSua;
    private javax.swing.JButton btPNHThem;
    private javax.swing.JButton btPNHThem1;
    private javax.swing.JButton btPNHTim;
    private javax.swing.JButton btPNHXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCTNHCong;
    private javax.swing.JLabel lbCTNHSL;
    private javax.swing.JLabel lbCTNHTru;
    private javax.swing.JTable tbCTNH;
    private javax.swing.JTable tbMH;
    private javax.swing.JTable tbPNH;
    private javax.swing.JTextField tfCTNHDG;
    private javax.swing.JTextField tfCTNHMHH;
    private javax.swing.JTextField tfCTNHMPN;
    private javax.swing.JTextField tfCTNHTT;
    private javax.swing.JTextField tfMHDG;
    private javax.swing.JTextField tfMHMHH;
    private javax.swing.JTextField tfMHSL;
    private javax.swing.JTextField tfMHTH;
    private javax.swing.JTextField tfPNHMNV;
    private javax.swing.JTextField tfPNHMPNH;
    private javax.swing.JTextField tfPNHNCC;
    private javax.swing.JTextField tfPNHNNH;
    private javax.swing.JTextField tfPNHTT;
    private javax.swing.JTabbedPane tpNhapHang;
    // End of variables declaration//GEN-END:variables
}
