/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.HopDongThuePhongBUS;
import qlks.BUS.LoaiPhongBUS;
import qlks.BUS.PhongBUS;
import qlks.DAO.LoaiPhongDAO;
import qlks.DTO.DanhMucKhuyenMai;
import qlks.DTO.DanhMucKhuyenMaiDTO;
import qlks.DTO.HoaDon;
import qlks.DTO.HoaDonDTO;
import qlks.DTO.HopDongThuePhong;
import qlks.DTO.HopDongThuePhongDTO;
import qlks.DTO.KhachHang;
import qlks.DTO.KhachHangDTO;
import qlks.DTO.LoaiPhong;
import qlks.DTO.LoaiPhongDTO;
import qlks.DTO.Phong;
import qlks.DTO.PhongDTO;
import qlks.DTO.SuDungDichVu;
import qlks.DTO.SuDungDichVuDTO;
import static qlks.GUI.MENUFORM.jPanelChane;
import static qlks.GUI.MENUFORM.jchild;
import qlks.Model.ModelHopDongThuePhong;
import qlks.Model.ModelLoaiPhong;
import qlks.Model.ModelPhong;

/**
 *
 * @author Nguyen Tien Dung
 */
public class phong extends javax.swing.JPanel {
    private LoaiPhongDTO lpDTO = new LoaiPhongDTO();
    private LoaiPhongBUS lpBUS = new LoaiPhongBUS();
    LoaiPhong lp;
    DefaultTableModel modellp;
    int rowlp = -1;
    //phong
    static PhongDTO pDTO = new PhongDTO();
    private PhongBUS pBUS = new PhongBUS();
    Phong p;
    DefaultTableModel modelp;
    int rowp = -1;
    //Hop dong phong
    static HopDongThuePhongDTO hdpDTO = new HopDongThuePhongDTO();
    private HopDongThuePhongBUS hdpBUS = new HopDongThuePhongBUS();
    HopDongThuePhong hdp;
    DefaultTableModel modelhd;
    int rowhd = -1;
    //ds nhan vao conbobox
    ArrayList<Phong> ds = null;
    ArrayList<Phong> dst = null;
    String MaLoai = "0";
    
    
    //Bien static
    static String hdpMaPhong = "";
    static String hdpGiaTien = "";
    
    //Bien static tu Su Dung Dich Vu
    static boolean hdpSuDungDichVu = false;
    
    /**
     * Creates new form phong
     */
    public phong() {
        initComponents();
        
        hienThiDanhSachPhong();
    }
    
    public void hienThiDanhSachPhong() {
        //Loai phong
        modellp = new ModelLoaiPhong(lpBUS.docDanhSachLoaiPhong()).getModel();
        tbLP.setModel(modellp);
        //Phong
        modelp = new ModelPhong(pBUS.docDanhSachPhong()).getModel();
        tbP.setModel(modelp);
        //Tu dong dien
        if(MENUFORM.pMaKhachHang){
            tbPane.setSelectedIndex(1);
            MENUFORM.pMaKhachHang = false;
            tfMKHHD.setText(MENUFORM.dlMaKhachHang);
            tfMKHHD.setEditable(false);
            tfMPHD.setText(hdpMaPhong);
            tfMPHD.setEditable(false);
            tfTPHD.setText(hdpGiaTien);
            tfTPHD.setEditable(false);
        }
        tfNThHD.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        
        //Hop dong thue phong
        tfMNVHD.setText(MENUFORM.maNhanVien);
        if(hdpSuDungDichVu){
            tbPane.setSelectedIndex(1);
            hdpSuDungDichVu = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        tbPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLP = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfLPTLP = new javax.swing.JTextField();
        tfLPMLP = new javax.swing.JTextField();
        tfLPSN = new javax.swing.JTextField();
        tfLPGT = new javax.swing.JTextField();
        btLPT = new javax.swing.JButton();
        btLPX = new javax.swing.JButton();
        btLPS = new javax.swing.JButton();
        btLPC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        tfPMP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfPTP = new javax.swing.JTextField();
        tfPLP = new javax.swing.JTextField();
        btPS = new javax.swing.JButton();
        btPM = new javax.swing.JButton();
        btPDK = new javax.swing.JButton();
        btPBT = new javax.swing.JButton();
        btPTT = new javax.swing.JButton();
        cbPTT = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNThHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfMNVHD = new javax.swing.JTextField();
        tfMKHHD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTPHD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMPHD = new javax.swing.JTextField();
        btthemHDTP = new javax.swing.JButton();
        btSuaHDTP = new javax.swing.JButton();
        btHDTPXoa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfNTrHD = new javax.swing.JTextField();
        btChamKH = new javax.swing.JButton();
        btClearHP = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taHDGC = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbThanhToan = new javax.swing.JComboBox<>();
        btChamN = new javax.swing.JButton();
        btHDPDichVu = new javax.swing.JButton();
        btHDPKhuyenMai = new javax.swing.JButton();
        btChamKH1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHDP = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        tbPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbPaneStateChanged(evt);
            }
        });
        tbPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPaneMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "QUẢN LÝ PHÒNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N

        jPanel18.setBackground(new java.awt.Color(204, 153, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Loại phòng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        tbLP.setBackground(new java.awt.Color(255, 255, 204));
        tbLP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbLPMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbLP);

        jLabel8.setText("Mã loại phòng");

        jLabel9.setText("Tên loại phòng ");

        jLabel10.setText("Số người");

        jLabel11.setText("Giá tiền");

        tfLPTLP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLPTLPKeyPressed(evt);
            }
        });

        tfLPMLP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLPMLPKeyPressed(evt);
            }
        });

        tfLPSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLPSNActionPerformed(evt);
            }
        });
        tfLPSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLPSNKeyPressed(evt);
            }
        });

        btLPT.setBackground(new java.awt.Color(0, 153, 153));
        btLPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btLPT.setText("Thêm");
        btLPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLPTActionPerformed(evt);
            }
        });

        btLPX.setBackground(new java.awt.Color(0, 153, 153));
        btLPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btLPX.setText("Xóa");
        btLPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLPXActionPerformed(evt);
            }
        });

        btLPS.setBackground(new java.awt.Color(0, 153, 153));
        btLPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btLPS.setText("Sửa");
        btLPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLPSActionPerformed(evt);
            }
        });

        btLPC.setBackground(new java.awt.Color(0, 153, 153));
        btLPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btLPC.setText("Clear");
        btLPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLPSN)
                            .addComponent(tfLPTLP)
                            .addComponent(tfLPMLP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfLPGT, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLPT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLPX, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfLPMLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLPTLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfLPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfLPGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLPT)
                    .addComponent(btLPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLPX)
                    .addComponent(btLPC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel29.setText("Mã Phòng");

        tfPMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPMPKeyPressed(evt);
            }
        });

        jLabel30.setText("Tên Phòng");

        jLabel31.setText("Loại Phòng");

        tfPTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPTPKeyPressed(evt);
            }
        });

        btPS.setBackground(new java.awt.Color(0, 153, 153));
        btPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btPS.setText("Sửa");
        btPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPSActionPerformed(evt);
            }
        });

        btPM.setBackground(new java.awt.Color(0, 153, 153));
        btPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/open.png"))); // NOI18N
        btPM.setText("Mở");
        btPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPMActionPerformed(evt);
            }
        });

        btPDK.setBackground(new java.awt.Color(0, 153, 153));
        btPDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/edit.png"))); // NOI18N
        btPDK.setText("Đăng ký");
        btPDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDKActionPerformed(evt);
            }
        });

        btPBT.setBackground(new java.awt.Color(0, 153, 153));
        btPBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/close.png"))); // NOI18N
        btPBT.setText("Bảo trì");
        btPBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPBTActionPerformed(evt);
            }
        });

        btPTT.setBackground(new java.awt.Color(0, 153, 153));
        btPTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/contract.png"))); // NOI18N
        btPTT.setText("Thanh toán");
        btPTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPTTActionPerformed(evt);
            }
        });

        cbPTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đã dùng", "Bảo trì" }));
        cbPTT.setToolTipText("");
        cbPTT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbPTTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbPTTFocusLost(evt);
            }
        });
        cbPTT.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                cbPTTMouseWheelMoved(evt);
            }
        });
        cbPTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPTTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbPTTMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbPTTMouseReleased(evt);
            }
        });
        cbPTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(tfPLP, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPTP, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfPMP))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cbPTT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPDK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPTT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tfPMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPM)
                    .addComponent(cbPTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfPTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPBT)
                    .addComponent(btPDK))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tfPLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPS)
                    .addComponent(btPTT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbP.setBackground(new java.awt.Color(255, 255, 204));
        tbP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbPMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(56, 56, 56))
        );

        tbPane.addTab("Quản lí phòng", jPanel5);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/hopdong.png"))); // NOI18N
        jLabel4.setText("HỢP ĐỒNG THUÊ PHÒNG");

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết thuê phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel1.setText("Số hợp đồng");

        tfSHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSHDKeyPressed(evt);
            }
        });

        jLabel2.setText("Mã nhân viên");

        tfNThHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNThHDKeyPressed(evt);
            }
        });

        jLabel3.setText("Mã phòng");

        jLabel5.setText("Mã khách hàng");

        tfMNVHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMNVHDKeyPressed(evt);
            }
        });

        tfMKHHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMKHHDKeyPressed(evt);
            }
        });

        jLabel6.setText("Tiền phòng");

        tfTPHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTPHDKeyPressed(evt);
            }
        });

        jLabel7.setText("Ngày thuê");

        tfMPHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMPHDKeyPressed(evt);
            }
        });

        btthemHDTP.setBackground(new java.awt.Color(0, 153, 153));
        btthemHDTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btthemHDTP.setText("Thêm");
        btthemHDTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemHDTPActionPerformed(evt);
            }
        });

        btSuaHDTP.setBackground(new java.awt.Color(0, 153, 153));
        btSuaHDTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        btSuaHDTP.setText("Sửa");
        btSuaHDTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaHDTPActionPerformed(evt);
            }
        });

        btHDTPXoa.setBackground(new java.awt.Color(0, 153, 153));
        btHDTPXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        btHDTPXoa.setText("Xóa");
        btHDTPXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDTPXoaActionPerformed(evt);
            }
        });

        jLabel12.setText("Ngày trả");

        tfNTrHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNTrHDKeyPressed(evt);
            }
        });

        btChamKH.setText("...");
        btChamKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChamKHActionPerformed(evt);
            }
        });

        btClearHP.setBackground(new java.awt.Color(0, 153, 153));
        btClearHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btClearHP.setText("Clear");
        btClearHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearHPActionPerformed(evt);
            }
        });

        taHDGC.setColumns(20);
        taHDGC.setRows(5);
        jScrollPane4.setViewportView(taHDGC);

        jLabel13.setText("Ghi chú ");

        jLabel14.setText("Trạng thái");

        cbThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đã thanh toán" }));

        btChamN.setText("...");
        btChamN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChamNActionPerformed(evt);
            }
        });

        btHDPDichVu.setBackground(new java.awt.Color(0, 153, 153));
        btHDPDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btHDPDichVu.setText("Dịch vụ");
        btHDPDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDPDichVuActionPerformed(evt);
            }
        });

        btHDPKhuyenMai.setBackground(new java.awt.Color(0, 153, 153));
        btHDPKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        btHDPKhuyenMai.setText("Khuyến mãi");
        btHDPKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDPKhuyenMaiActionPerformed(evt);
            }
        });

        btChamKH1.setText("...");
        btChamKH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChamKH1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTPHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfMKHHD, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btChamKH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNTrHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMPHD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(tfNThHD)
                                .addGap(18, 18, 18)
                                .addComponent(btChamN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(tfMNVHD)
                                .addGap(18, 18, 18)
                                .addComponent(btChamKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btthemHDTP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSuaHDTP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btHDTPXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btClearHP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btHDPDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btHDPKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMNVHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChamKH1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMPHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMKHHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChamKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTPHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNThHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChamN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfNTrHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cbThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btthemHDTP)
                    .addComponent(btSuaHDTP))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHDTPXoa)
                    .addComponent(btClearHP))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHDPDichVu)
                    .addComponent(btHDPKhuyenMai))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tbHDP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã nhân viên", "Mã phòng", "Mã khách hàng", "Ngày thuê", "Ngày trả"
            }
        ));
        tbHDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbHDPMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbHDP);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/search.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbPane.addTab("Quản lí hợp đồng thuê phòng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLPMouseClicked

    }//GEN-LAST:event_tbLPMouseClicked

    private void tfLPSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLPSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLPSNActionPerformed

    private void btLPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLPTActionPerformed
        if(tfLPMLP.getText().length()>0&&tfLPTLP.getText().length()>0&&
            tfLPSN.getText().length()>0&&tfLPGT.getText().length()>0){
            lp = new LoaiPhong();
            lp.setMaLoaiPhong(tfLPMLP.getText());
            lp.setTenLoaiPhong(tfLPTLP.getText());
            if(lp.setSoNguoi(tfLPSN.getText()) == false){
                return;
            }
            if(lp.setGiaTien(tfLPGT.getText()) == false){
                return;
            }
            if(lpBUS.themLoaiPhong(lpDTO, lp)){
                modellp = new ModelLoaiPhong(lpBUS.docDanhSachLoaiPhong()).getModel();
                tbLP.setModel(modellp);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btLPTActionPerformed

    private void btLPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLPXActionPerformed
        if(tfLPMLP.getText().length()>0){
            if(lpBUS.xoaLoaiPhong(lpDTO, lp)){
                modelp = new ModelLoaiPhong(lpDTO.docDanhSachLoaiPhong()).getModel();
                tbLP.setModel(modelp);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã loại phòng");
        }
    }//GEN-LAST:event_btLPXActionPerformed

    private void btLPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLPSActionPerformed
        if(tfLPMLP.getText().length()>0&&tfLPTLP.getText().length()>0&&
            tfLPSN.getText().length()>0&&tfLPGT.getText().length()>0){
            lp = new LoaiPhong();
            lp.setMaLoaiPhong(tfLPMLP.getText());
            lp.setTenLoaiPhong(tfLPTLP.getText());
            if(lp.setSoNguoi(tfLPSN.getText()) == false){
                return;
            }
            if(lp.setGiaTien(tfLPGT.getText()) == false){
                return;
            }
            if(lpBUS.suaLoaiPhong(lpDTO,lp)){
                tbLP.setModel(new ModelLoaiPhong(lpDTO.docDanhSachLoaiPhong()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btLPSActionPerformed

    private void btPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPSActionPerformed
        if(tfPMP.getText().length()>0&&tfPTP.getText().length()>0&&tfPLP.getText().length()>0){
            p = new Phong();
            p.setMaPhong(tfPMP.getText());
            p.setTenPhong(tfPTP.getText());
            String mlp = "";
            for(LoaiPhong lpt: lpDTO.docDanhSachLoaiPhong()){
                if(tfPLP.getText().compareTo(lpt.getTenLoaiPhong())==0){
                    mlp = lpt.getMaLoaiPhong();
                    break;
                }
            }
            p.setMaLoaiPhong(mlp);
            p.setTinhTrang(cbPTT.getItemAt(cbPTT.getSelectedIndex()));
            if(pBUS.suaPhong(pDTO,p)){
                tfPMP.setText("");
                tfPTP.setText("");
                tfPLP.setText("");
                cbPTT.setSelectedIndex(0);
                ds = null;
                dst = null;
                MaLoai = "0";
                String MaLoai = "0";
                tbP.setModel(new ModelPhong(pDTO.docDanhSachPhong()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPSActionPerformed

    private void btPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPMActionPerformed
        if(tfPMP.getText().length()>0&&tfPTP.getText().length()>0&&tfPLP.getText().length()>0){
            p = new Phong();
            p.setMaPhong(tfPMP.getText());
            p.setTenPhong(tfPTP.getText());
            String mlp = "";
            for(LoaiPhong lpt: lpDTO.docDanhSachLoaiPhong()){
                if(tfPLP.getText().compareTo(lpt.getTenLoaiPhong())==0){
                    mlp = lpt.getMaLoaiPhong();
                    break;
                }
            }
            p.setMaLoaiPhong(mlp);
            p.setTinhTrang("Trống");
            if(pBUS.suaPhong(pDTO,p)){
                tfPMP.setText("");
                tfPTP.setText("");
                tfPLP.setText("");
                cbPTT.setSelectedIndex(0);
                ds = null;
                dst = null;
                MaLoai = "0";
                String MaLoai = "0";
                tbP.setModel(new ModelPhong(pDTO.docDanhSachPhong()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPMActionPerformed

    private void btPDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDKActionPerformed
        if(tfPMP.getText().length()>0&&tfPTP.getText().length()>0&&tfPLP.getText().length()>0){
            if(JOptionPane.YES_OPTION==JOptionPane.showConfirmDialog(null, "Đăng ký")){
                tbPane.setSelectedIndex(1);
                tfMPHD.setText(tfPMP.getText());
                tfMPHD.setEditable(false);
                hdpMaPhong = tfPMP.getText();
                for(LoaiPhong lp: lpDTO.docDanhSachLoaiPhong()){
                    if(tfPLP.getText().compareTo(lp.getTenLoaiPhong())==0){
                        hdpGiaTien = lp.getGiaTien()+"";
                        tfTPHD.setText(hdpGiaTien);
                    }
                }
                
                tfTPHD.setEditable(false);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPDKActionPerformed

    private void btPBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPBTActionPerformed
        if(tfPMP.getText().length()>0&&tfPTP.getText().length()>0&&tfPLP.getText().length()>0){
            p = new Phong();
            p.setMaPhong(tfPMP.getText());
            p.setTenPhong(tfPTP.getText());
            String mlp = "";
            for(LoaiPhong lpt: lpDTO.docDanhSachLoaiPhong()){
                if(tfPLP.getText().compareTo(lpt.getTenLoaiPhong())==0){
                    mlp = lpt.getMaLoaiPhong();
                    break;
                }
            }
            p.setMaLoaiPhong(mlp);
            p.setTinhTrang("Bảo trì");
            if(pBUS.suaPhong(pDTO,p)){
                tfPMP.setText("");
                tfPTP.setText("");
                tfPLP.setText("");
                cbPTT.setSelectedIndex(0);
                ds = null;
                dst = null;
                MaLoai = "0";
                String MaLoai = "0";
                tbP.setModel(new ModelPhong(pDTO.docDanhSachPhong()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btPBTActionPerformed

    private void btPTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPTTActionPerformed
        PhieuThanhToan.pSoHopDong = "";
        PhieuThanhToan.pMaNhanVien = "";
        PhieuThanhToan.pPhong = 0;
        PhieuThanhToan.pDichVu = 0;
        PhieuThanhToan.pKhuyenMaiPhong = 0;
        PhieuThanhToan.pKhuyenMaiDichVu= 0;
        if(tfPMP.getText().length()>0&&tfPTP.getText().length()>0&&tfPLP.getText().length()>0){
            if(JOptionPane.YES_OPTION==JOptionPane.showConfirmDialog(null, "Thanh toán")){
                
                for(HopDongThuePhong hdpt: hdpDTO.docDanhSachHopDongThuePhong()){
                    if(hdpt.getMaPhong().compareTo(tfPMP.getText())==0 && hdpt.getTrangThai().compareTo("Chưa thanh toán")==0){
                        PhieuThanhToan.pMaNhanVien = hdpt.getMaNhanVien();
                        PhieuThanhToan.pSoHopDong = hdpt.getSoHopDongThuePhong();
                        for(LoaiPhong lpt: lpDTO.docDanhSachLoaiPhong()){
                            if(lpt.getTenLoaiPhong().compareTo(tfPLP.getText())==0){
                                PhieuThanhToan.pPhong = Integer.valueOf(lpt.getGiaTien());
                                break;
                            }
                        }
                        for(SuDungDichVu sddvt: new SuDungDichVuDTO().docDanhSachSuDungDichVu()){
                            if(PhieuThanhToan.pSoHopDong.compareTo(sddvt.getSoHopDongTHuePhong())==0){
                                PhieuThanhToan.pDichVu += sddvt.getThanhTien();
                            }
                        }
                        for(DanhMucKhuyenMai dmkmt: new DanhMucKhuyenMaiDTO().docDanhSachDanhMucKhuyenMai()){
                            if(PhieuThanhToan.pSoHopDong.compareTo(dmkmt.getSoHopDongThuePhong())==0){
                                if(dmkmt.getLoaiKhuyenMai().compareTo("Dịch vụ")==0){
                                    PhieuThanhToan.pKhuyenMaiDichVu = dmkmt.getGiamGia();
                                }else{
                                    PhieuThanhToan.pKhuyenMaiPhong = dmkmt.getGiamGia();
                                }
                            }
                        }
                    }
                }
                PhieuThanhToan ptt = new PhieuThanhToan();
                ptt.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }        
    }//GEN-LAST:event_btPTTActionPerformed

    private void cbPTTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPTTFocusGained

    }//GEN-LAST:event_cbPTTFocusGained

    private void cbPTTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPTTFocusLost

    }//GEN-LAST:event_cbPTTFocusLost

    private void cbPTTMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_cbPTTMouseWheelMoved

    }//GEN-LAST:event_cbPTTMouseWheelMoved

    private void cbPTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPTTMouseClicked

    }//GEN-LAST:event_cbPTTMouseClicked

    private void cbPTTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPTTMouseEntered

    }//GEN-LAST:event_cbPTTMouseEntered

    private void cbPTTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPTTMouseReleased

    }//GEN-LAST:event_cbPTTMouseReleased

    private void cbPTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPTTActionPerformed
        if(cbPTT.isFocusOwner()){
            int i = cbPTT.getSelectedIndex();
            ds = pDTO.danhSachTinhTrangPhong(i,MaLoai);
            dst = ds;
            modelp = new ModelPhong(ds).getModel();
            tbP.setModel(modelp);
        }
    }//GEN-LAST:event_cbPTTActionPerformed

    private void tbPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPMouseClicked

    }//GEN-LAST:event_tbPMouseClicked

    private void btLPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLPCActionPerformed
        tfLPMLP.setText("");
        tfLPTLP.setText("");
        tfLPSN.setText("");
        tfLPGT.setText("");
        tfPMP.setText("");
        tfPTP.setText("");
        tfPLP.setText("");
        cbPTT.setSelectedIndex(0);
        ds = null;
        dst = null;
        MaLoai = "0";
        String MaLoai = "0";

        tbP.setModel(new ModelPhong(pDTO.docDanhSachPhong()).getModel());

        tbLP.setModel(new ModelLoaiPhong(lpDTO.docDanhSachLoaiPhong()).getModel());
    }//GEN-LAST:event_btLPCActionPerformed

    private void tbHDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDPMouseClicked
        
    }//GEN-LAST:event_tbHDPMouseClicked

    private void btClearHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearHPActionPerformed
        tfMPHD.setEditable(true);
        tfMKHHD.setEditable(true);
        tfTPHD.setEditable(true);
        int size = hdpDTO.docDanhSachHopDongThuePhong().size();
        int ishd = (size <= 0 ? 0 : Integer.valueOf(hdpDTO.docDanhSachHopDongThuePhong().get(size-1).getSoHopDongThuePhong())+1);
        tfSHD.setText(ishd+"");
        tfMPHD.setText("");
        tfMNVHD.setText("");
        tfMPHD.setText("");
        tfTPHD.setText("");
        tfNThHD.setText("");
        tfNTrHD.setText("");
        tfMKHHD.setText("");
        taHDGC.setText("");
        cbThanhToan.setSelectedIndex(0);

        tbHDP.setModel(new ModelHopDongThuePhong(hdpDTO.docDanhSachHopDongThuePhong()).getModel());
    }//GEN-LAST:event_btClearHPActionPerformed

    private void tbPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbPaneStateChanged
        if(tbPane.getSelectedIndex()==1){
            modelhd = new ModelHopDongThuePhong(hdpDTO.docDanhSachHopDongThuePhong()).getModel();
            tbHDP.setModel(modelhd);
            //Tu dong diem
            int size = hdpDTO.docDanhSachHopDongThuePhong().size();
            int ishd = (size <= 0 ? 0 : Integer.valueOf(hdpDTO.docDanhSachHopDongThuePhong().get(size-1).getSoHopDongThuePhong())+1);
            tfSHD.setText(ishd+"");
        }else{
            if(tbPane.getSelectedIndex()==0){
                tfLPMLP.setText("");
                tfLPTLP.setText("");
                tfLPSN.setText("");
                tfLPGT.setText("");
                tfPMP.setText("");
                tfPTP.setText("");
                tfPLP.setText("");
                cbPTT.setSelectedIndex(0);
                ds = null;
                dst = null;
                MaLoai = "0";
                String MaLoai = "0";

                modelp = new ModelPhong(pDTO.docDanhSachPhong()).getModel();
                tbP.setModel(modelp);

                modellp = new ModelLoaiPhong(lpDTO.docDanhSachLoaiPhong()).getModel();
                tbLP.setModel(modellp);
            }
        }
    }//GEN-LAST:event_tbPaneStateChanged

    private void tbPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPaneMouseClicked
        tfMPHD.setEditable(true);
    }//GEN-LAST:event_tbPaneMouseClicked

    private void btHDTPXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDTPXoaActionPerformed
        if(tfSHD.getText().length()>0){
            if(hdpBUS.xoaHopDongThuePhong(hdpDTO, tfSHD.getText())){
                modelhd = new ModelHopDongThuePhong(hdpDTO.docDanhSachHopDongThuePhong()).getModel();
                tbHDP.setModel(modelhd);
            }
        }
    }//GEN-LAST:event_btHDTPXoaActionPerformed

    private void btSuaHDTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaHDTPActionPerformed
        if(tfMPHD.getText().length()>0&&tfMNVHD.getText().length()>0&&tfMPHD.getText().length()>0&&
                tfMKHHD.getText().length()>0&&tfTPHD.getText().length()>0&&tfNThHD.getText().length()>0&&
                tfNTrHD.getText().length()>0){
            hdp = new HopDongThuePhong();
            if(hdp.setSoHopDongThuePhongKT(tfSHD.getText()) == false){
                return;
            }
            hdp.setMaKhachHang(tfMKHHD.getText());
            hdp.setMaNhanVien(tfMNVHD.getText());
            hdp.setMaPhong(tfMPHD.getText());
            if(hdp.setTienPhong(tfTPHD.getText()) == false){
                return;
            }
            if(hdp.setNgayThueKT(tfNThHD.getText()) == false){
                return;
            }
            if(hdp.setNgayTraKT(tfNTrHD.getText(),tfNThHD.getText()) == false){
                return;
            }
            hdp.setTrangThai(cbThanhToan.getItemAt(cbThanhToan.getSelectedIndex()));
            hdp.setGhiChu(taHDGC.getText());
            
            
            if(hdpBUS.suaHopDongThuePhong(hdpDTO, hdp)){
                if(hdp.getTrangThai().compareTo("Chưa thanh toán")==0){
                    p = pDTO.getPhong(hdp.getMaPhong());
                    p.setTinhTrang("Đã dùng");
                    pBUS.suaPhong(pDTO, p);
                }else{
                    if(hdp.getTrangThai().compareTo("Đã thanh toán")==0){
                        p = pDTO.getPhong(hdp.getMaPhong());
                    p.setTinhTrang("Trống");
                    pBUS.suaPhong(pDTO, p);
                    }
                }

                Vector vt = new Vector();
                hdp = new HopDongThuePhong();
                vt.add(tfSHD.getText());
                vt.add(tfMNVHD.getText());
                vt.add(tfMPHD.getText());
                vt.add(tfMKHHD.getText());
                vt.add(tfTPHD.getText());
                vt.add(tfNThHD.getText());
                vt.add(tfNTrHD.getText());
                vt.add(cbThanhToan.getItemAt(cbThanhToan.getSelectedIndex()));
                vt.add(taHDGC.getText());
                
                tbHDP.setModel(new ModelHopDongThuePhong(hdpDTO.docDanhSachHopDongThuePhong()).getModel());
            }
        }
    }//GEN-LAST:event_btSuaHDTPActionPerformed

    private void btthemHDTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemHDTPActionPerformed
        if(tfMPHD.getText().length()>0&&tfMNVHD.getText().length()>0&&tfMPHD.getText().length()>0&&
                tfMKHHD.getText().length()>0&&tfTPHD.getText().length()>0&&tfNThHD.getText().length()>0&&
                tfNTrHD.getText().length()>0){
            hdp = new HopDongThuePhong();
            if(hdp.setSoHopDongThuePhongKT(tfSHD.getText()) == false){
                return;
            }
            hdp.setMaKhachHang(tfMKHHD.getText());
            hdp.setMaNhanVien(tfMNVHD.getText());
            hdp.setMaPhong(tfMPHD.getText());
            if(hdp.setTienPhong(tfTPHD.getText()) == false){
                return;
            }
            if(hdp.setNgayThueKT(tfNThHD.getText()) == false){
                return;
            }
            if(hdp.setNgayTraKT(tfNTrHD.getText(),tfNThHD.getText()) == false){
                return;
            }
            hdp.setTrangThai(cbThanhToan.getItemAt(cbThanhToan.getSelectedIndex()));
            hdp.setGhiChu(taHDGC.getText());
            
            if(hdpBUS.themHopDongThuePhong(hdpDTO, hdp)){
                if(hdp.getTrangThai().compareTo("Chưa thanh toán")==0){
                    p = pDTO.getPhong(hdp.getMaPhong());
                    p.setTinhTrang("Đã dùng");
                    pBUS.suaPhong(pDTO, p);
                }

                Vector vt = new Vector();
                hdp = new HopDongThuePhong();
                vt.add(tfSHD.getText());
                vt.add(tfMNVHD.getText());
                vt.add(tfMPHD.getText());
                vt.add(tfMKHHD.getText());
                vt.add(tfTPHD.getText());
                vt.add(tfNThHD.getText());
                vt.add(tfNTrHD.getText());
                vt.add(cbThanhToan.getItemAt(cbThanhToan.getSelectedIndex()));
                vt.add(taHDGC.getText());
                
                tbHDP.setModel(new ModelHopDongThuePhong(hdpDTO.docDanhSachHopDongThuePhong()).getModel());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
    }//GEN-LAST:event_btthemHDTPActionPerformed

    private void btChamKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChamKHActionPerformed
        MENUFORM.khMaKhachHang = true;
        jchild=new khachhang();
        jPanelChane.removeAll();
        jPanelChane.add(jchild);
        jPanelChane.validate();
        
        MENUFORM.btNhanVien.setBackground(Color.WHITE);
        MENUFORM.btKhachHang.setBackground(Color.YELLOW);
        MENUFORM.btDVKM.setBackground(Color.WHITE);
        MENUFORM.btPhong.setBackground(Color.WHITE);
        MENUFORM.btHoaDon.setBackground(Color.WHITE);
        MENUFORM.btNhapHang.setBackground(Color.WHITE);
    }//GEN-LAST:event_btChamKHActionPerformed

    private void tbHDPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDPMousePressed
        rowhd = tbHDP.getSelectedRow();

        tfSHD.setText(modelhd.getValueAt(rowhd, 0).toString());
        tfMNVHD.setText(modelhd.getValueAt(rowhd, 1).toString());
        tfMPHD.setText(modelhd.getValueAt(rowhd, 2).toString());
        String mkh = "";
        for(KhachHang kht: new KhachHangDTO().docDanhSachKhachHang()){
            if(modelhd.getValueAt(rowhd, 3).toString().compareTo(kht.getHo()+" "+kht.getTen())==0){
                mkh = kht.getMaKhachHang();
            }
        }
        tfMKHHD.setText(mkh);
        tfTPHD.setText(modelhd.getValueAt(rowhd, 4).toString());
        tfNThHD.setText(modelhd.getValueAt(rowhd, 5).toString());
        tfNTrHD.setText(modelhd.getValueAt(rowhd, 6).toString());
        if(modelhd.getValueAt(rowhd, 7).toString().compareTo("Đã thanh toán")==0){
            cbThanhToan.setSelectedIndex(1);
        }else{
            if(modelhd.getValueAt(rowhd, 7).toString().compareTo("Chưa thanh toán")==0){
                cbThanhToan.setSelectedIndex(0);
            }
        }
        taHDGC.setText(modelhd.getValueAt(rowhd, 8).toString());
    }//GEN-LAST:event_tbHDPMousePressed

    private void tbPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPMousePressed
        rowp = tbP.getSelectedRow();
        if(dst==null){
            p = pDTO.getPhong(rowp);
        }else{
            p = dst.get(rowp);
        }
        String tlp = "";
        LoaiPhongDAO lpDAO = new LoaiPhongDAO();
        tfPMP.setText(p.getMaPhong());
        tfPTP.setText(p.getTenPhong());
        for(LoaiPhong lp: lpDAO.docDanhSachLoaiPhong()){
            if(lp.getMaLoaiPhong().compareTo(p.getMaLoaiPhong())==0){
                tlp = lp.getTenLoaiPhong();
                break;
            }
        }
        tfPLP.setText(tlp);
        if(p.getTinhTrang().compareTo("Trống")==0){
            cbPTT.setSelectedIndex(0);
        }else{
            if(p.getTinhTrang().compareTo("Đã dùng")==0){
                cbPTT.setSelectedIndex(1);
            }else{
                cbPTT.setSelectedIndex(2);
            }
        }
        if(p.getTinhTrang().compareTo("Bảo trì")==0){
            btPDK.setEnabled(false);
            btPTT.setEnabled(false);
            btPBT.setEnabled(false);
            btPM.setEnabled(true);
        }else{
            if(p.getTinhTrang().compareTo("Trống")==0){
                btPDK.setEnabled(true);
                btPTT.setEnabled(false);
                btPBT.setEnabled(true);
                btPM.setEnabled(false);
            }else{
                btPDK.setEnabled(false);
                btPTT.setEnabled(true);
                btPBT.setEnabled(false);
                btPM.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tbPMousePressed

    private void tbLPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLPMousePressed
        rowlp = tbLP.getSelectedRow();

        lp = lpDTO.getLoaiPhong(rowlp);
        tfLPMLP.setText(lp.getMaLoaiPhong());
        tfLPTLP.setText(lp.getTenLoaiPhong());
        tfLPSN.setText(lp.getSoNguoi()+"");
        tfLPGT.setText(lp.getGiaTien()+"");

        MaLoai = lp.getMaLoaiPhong();
        //Thay doi phong table
        ArrayList<Phong> dsmp = null;
        if(ds==null){
            dsmp = pDTO.danhSachMaLoaiPhong(lp.getMaLoaiPhong());
            dst = dsmp;
            modelp = new ModelPhong(dsmp).getModel();
            tbP.setModel(modelp);
        }else{
            dsmp = new ArrayList<>();
            for(Phong pt: ds){
                if(pt.getMaLoaiPhong().compareTo(lp.getMaLoaiPhong())==0){
                    dsmp.add(pt);
                }
            }
            dst = dsmp;
            modelp = new ModelPhong(dsmp).getModel();
            tbP.setModel(modelp);
        }
    }//GEN-LAST:event_tbLPMousePressed

    private void btChamNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChamNActionPerformed
        tfNThHD.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }//GEN-LAST:event_btChamNActionPerformed

    private void btHDPDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDPDichVuActionPerformed
        if(tfSHD.getText().length()>0){
            dichvu.sddvSoHopDongThuePhong = tfSHD.getText();
            MENUFORM.formatButton(2);
        }
    }//GEN-LAST:event_btHDPDichVuActionPerformed

    private void btHDPKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDPKhuyenMaiActionPerformed
        if(tfSHD.getText().length()>0){
            dichvu.dmkmSoHopDongThuePhong = tfSHD.getText();
            MENUFORM.formatButton(2);
            
        }
    }//GEN-LAST:event_btHDPKhuyenMaiActionPerformed

    private void btChamKH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChamKH1ActionPerformed
        tfMNVHD.setText(MENUFORM.maNhanVien);
    }//GEN-LAST:event_btChamKH1ActionPerformed

    private void tfLPMLPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLPMLPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfLPTLP.requestFocus();
        }
    }//GEN-LAST:event_tfLPMLPKeyPressed

    private void tfLPTLPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLPTLPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfLPSN.requestFocus();
        }
    }//GEN-LAST:event_tfLPTLPKeyPressed

    private void tfLPSNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLPSNKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfLPGT.requestFocus();
        }
    }//GEN-LAST:event_tfLPSNKeyPressed

    private void tfPMPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPMPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPTP.requestFocus();
        }
    }//GEN-LAST:event_tfPMPKeyPressed

    private void tfPTPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPTPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfPLP.requestFocus();
        }
    }//GEN-LAST:event_tfPTPKeyPressed

    private void tfSHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMNVHD.requestFocus();
        }
    }//GEN-LAST:event_tfSHDKeyPressed

    private void tfMNVHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMNVHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMPHD.requestFocus();
        }
    }//GEN-LAST:event_tfMNVHDKeyPressed

    private void tfMPHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMPHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfMKHHD.requestFocus();
        }
    }//GEN-LAST:event_tfMPHDKeyPressed

    private void tfMKHHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMKHHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfTPHD.requestFocus();
        }
    }//GEN-LAST:event_tfMKHHDKeyPressed

    private void tfTPHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTPHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfNThHD.requestFocus();
        }
    }//GEN-LAST:event_tfTPHDKeyPressed

    private void tfNThHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNThHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfNTrHD.requestFocus();
        }
    }//GEN-LAST:event_tfNThHDKeyPressed

    private void tfNTrHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNTrHDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            taHDGC.requestFocus();
        }
    }//GEN-LAST:event_tfNTrHDKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int tienPhong = 0;
        try{
            tienPhong = Integer.parseInt(tfTPHD.getText());
        }catch(Exception e){
            tienPhong = -1;
        }
        
        hdp = new HopDongThuePhong();
            hdp.setSoHopDongThuePhong(tfSHD.getText());
            hdp.setMaKhachHang(tfMKHHD.getText());
            hdp.setMaNhanVien(tfMNVHD.getText());
            hdp.setMaPhong(tfMPHD.getText());
            hdp.setTienPhong(tienPhong);
            hdp.setNgayThue(tfNThHD.getText());
            hdp.setNgayTra(tfNTrHD.getText());
            hdp.setTrangThai(cbThanhToan.getItemAt(cbThanhToan.getSelectedIndex()));
            if(taHDGC.getText().length()>0){
                hdp.setGhiChu(taHDGC.getText());
            }else{
                //Tranh tim cac ghi chu chua khoang trang
                hdp.setGhiChu("!@#$%^&*()");
            }
            
            modelhd = new ModelHopDongThuePhong(hdpDTO.timHopDongThuePhong(hdp)).getModel();
            tbHDP.setModel(modelhd);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChamKH;
    private javax.swing.JButton btChamKH1;
    private javax.swing.JButton btChamN;
    private javax.swing.JButton btClearHP;
    private javax.swing.JButton btHDPDichVu;
    private javax.swing.JButton btHDPKhuyenMai;
    private javax.swing.JButton btHDTPXoa;
    private javax.swing.JButton btLPC;
    private javax.swing.JButton btLPS;
    private javax.swing.JButton btLPT;
    private javax.swing.JButton btLPX;
    private javax.swing.JButton btPBT;
    private javax.swing.JButton btPDK;
    private javax.swing.JButton btPM;
    private javax.swing.JButton btPS;
    private javax.swing.JButton btPTT;
    private javax.swing.JButton btSuaHDTP;
    private javax.swing.JButton btthemHDTP;
    private javax.swing.JComboBox<String> cbPTT;
    private javax.swing.JComboBox<String> cbThanhToan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea taHDGC;
    javax.swing.JTable tbHDP;
    private javax.swing.JTable tbLP;
    static javax.swing.JTable tbP;
    private javax.swing.JTabbedPane tbPane;
    private javax.swing.JTextField tfLPGT;
    private javax.swing.JTextField tfLPMLP;
    private javax.swing.JTextField tfLPSN;
    private javax.swing.JTextField tfLPTLP;
    private javax.swing.JTextField tfMKHHD;
    private javax.swing.JTextField tfMNVHD;
    private javax.swing.JTextField tfMPHD;
    private javax.swing.JTextField tfNThHD;
    private javax.swing.JTextField tfNTrHD;
    private javax.swing.JTextField tfPLP;
    private javax.swing.JTextField tfPMP;
    private javax.swing.JTextField tfPTP;
    private javax.swing.JTextField tfSHD;
    private javax.swing.JTextField tfTPHD;
    // End of variables declaration//GEN-END:variables
}
