/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import qlks.BUS.NhanVienBUS;
import qlks.DTO.NhanVien;
import qlks.DTO.NhanVienDTO;

/**
 *
 * @author admin
 */
public class TaiKhoan extends javax.swing.JPanel {
    ImageIcon imageIcon;
    Image image;
    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan() {
        initComponents();
        
        imageIcon = new ImageIcon(getClass().getResource("/qlks/hinh/logout.png"));
        image = imageIcon.getImage().getScaledInstance(130, 130, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(image);
        btDangXuat.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(getClass().getResource("/qlks/hinh/lock.png"));
        image = imageIcon.getImage().getScaledInstance(130, 130, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(image);
        btDoiMatKhau.setIcon(imageIcon);
        
        pnDMK.setVisible(false);
        
        for(NhanVien nv: new NhanVienDTO().docDanhSachNhanVien()){
            if(nv.getMaNhanVien().compareTo(MENUFORM.maNhanVien)==0){
                lbTen.setText(nv.getHo()+" "+nv.getTen());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btDangXuat = new javax.swing.JButton();
        btDoiMatKhau = new javax.swing.JButton();
        pnDMK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfMKM = new javax.swing.JTextField();
        tfXNMK = new javax.swing.JTextField();
        btHuy = new javax.swing.JButton();
        btDoi = new javax.swing.JButton();
        lbTen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Đăng xuất ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Đổi mật khẩu ");

        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        btDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoiMatKhauActionPerformed(evt);
            }
        });

        pnDMK.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi mật khẩu");
        jLabel1.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Mật khẩu mới");

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Xác nhận mật khẩu ");

        btHuy.setText("Hủy");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btDoi.setText("Đổi");
        btDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDMKLayout = new javax.swing.GroupLayout(pnDMK);
        pnDMK.setLayout(pnDMKLayout);
        pnDMKLayout.setHorizontalGroup(
            pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnDMKLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDMKLayout.createSequentialGroup()
                        .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(btDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDMKLayout.createSequentialGroup()
                        .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfXNMK)
                            .addComponent(tfMKM))))
                .addGap(68, 68, 68))
        );
        pnDMKLayout.setVerticalGroup(
            pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfXNMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDoi)
                    .addComponent(btHuy))
                .addGap(30, 30, 30))
        );

        lbTen.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lbTen.setForeground(new java.awt.Color(153, 0, 51));
        lbTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTen.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnDMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(jLabel2)
                            .addGap(366, 366, 366)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3))
                                .addComponent(btDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(232, 248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(pnDMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        MENUFORM.maNhanVien = "";
        MENUFORM.dongUngDung = true;
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiMatKhauActionPerformed
        pnDMK.setVisible(true);
    }//GEN-LAST:event_btDoiMatKhauActionPerformed

    private void btDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiActionPerformed
        if(tfMKM.getText().length()>0 && tfXNMK.getText().length()>0){
            if(tfMKM.getText().compareTo(tfXNMK.getText())==0){
                NhanVien nv = new NhanVienDTO().getNhanVien(MENUFORM.maNhanVien);
                nv.setMatKhau(tfXNMK.getText());
                NhanVienBUS nvBUS = new NhanVienBUS();
                if(nvBUS.doiMatKhauNhanVien(MENUFORM.maNhanVien, tfMKM.getText())){
                    JOptionPane.showMessageDialog(null, "Đổi thành công.");
                    pnDMK.setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nhập sai.");
            }

        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btDoiActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        pnDMK.setVisible(false);
    }//GEN-LAST:event_btHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btDoi;
    private javax.swing.JButton btDoiMatKhau;
    private javax.swing.JButton btHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbTen;
    private javax.swing.JPanel pnDMK;
    private javax.swing.JTextField tfMKM;
    private javax.swing.JTextField tfXNMK;
    // End of variables declaration//GEN-END:variables
}
