/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.GUI;


import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.Graphics2D;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import qlks.BUS.HoaDonBUS;
import qlks.BUS.ThongKeBUS;
import qlks.DTO.HoaDon;
import qlks.DTO.HoaDonDTO;
import qlks.DTO.PhieuNhapHangDTO;
import qlks.DTO.ReadWriteExcelFile;
import qlks.DTO.SuDungDichVuDTO;
import qlks.DTO.ThongKeDTO;
import qlks.Model.ModelThongKe;

/**
 *
 * @author VAN
 */
public class thongke extends javax.swing.JPanel {
    private ThongKeDTO tkDTO = new ThongKeDTO();
    private PhieuNhapHangDTO pnhDTO = new PhieuNhapHangDTO();
    DefaultTableModel modelhd;
    DefaultTableModel modelnh;
    private int tongThu = 0;
    private int tongChi = 0;
    /**
     * Creates new form thongke
     */
    public thongke() {
        initComponents();
        
        modelhd = new ModelThongKe().getModelhd(tkDTO.thongKe());
        tbTKHD.setModel(modelhd);
        
        modelnh = new ModelThongKe().getModelpnh(pnhDTO.docDanhSachPhieuNhapHang());
        tbPNH.setModel(modelnh);
              
        for(int i=0;i<modelhd.getRowCount();i++){
            tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
        }
        tfTKTT.setText(tongThu+"");
        
        for(int i=0;i<modelnh.getRowCount();i++){
            tongChi+=Integer.valueOf(modelnh.getValueAt(i, 2).toString());
        }
        tfTKTC.setText(tongChi+"");
        
        tfTKLN.setText((Integer.valueOf(tfTKTT.getText())-Integer.valueOf(tfTKTC.getText()))+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfTKMaNhanVien = new javax.swing.JTextField();
        btTKLocNhanVien = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfTKMaKhachHang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTKHD = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTKDenNgay = new javax.swing.JTextField();
        tfTKTuNgay = new javax.swing.JTextField();
        btTKNgay = new javax.swing.JButton();
        cbNgay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        rdMNV = new javax.swing.JRadioButton();
        rdMKH = new javax.swing.JRadioButton();
        rdNam = new javax.swing.JRadioButton();
        rdThang = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfTKTT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfTKTC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTKLN = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPNH = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 0, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)), "THỐNG KÊ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 255, 0))); // NOI18N
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Nhân viên - Khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel4.setText("Mã nhân viên");

        btTKLocNhanVien.setBackground(new java.awt.Color(0, 153, 153));
        btTKLocNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/filter.png"))); // NOI18N
        btTKLocNhanVien.setText("Lọc");
        btTKLocNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKLocNhanVienActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTKLocNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTKMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(tfTKMaKhachHang))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTKMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTKMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTKLocNhanVien)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        tbTKHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTKHD);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Ngày thanh toán", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel2.setText("Từ");

        jLabel3.setText(" Đến");

        tfTKDenNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTKDenNgayActionPerformed(evt);
            }
        });

        tfTKTuNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTKTuNgayActionPerformed(evt);
            }
        });

        btTKNgay.setBackground(new java.awt.Color(0, 153, 153));
        btTKNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/filter.png"))); // NOI18N
        btTKNgay.setText("Lọc");
        btTKNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKNgayActionPerformed(evt);
            }
        });

        cbNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu - Chi", "Ngày thuê" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTKNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTKTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tfTKDenNgay))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTKTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTKDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTKNgay)
                    .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Gom nhóm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        buttonGroup1.add(rdMNV);
        rdMNV.setText("Mã nhân viên ");
        rdMNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMNVActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMKH);
        rdMKH.setText("Mã khách hàng");
        rdMKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMKHActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNam);
        rdNam.setText("Năm");
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdThang);
        rdThang.setText("Tháng ");
        rdThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdMNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdMKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMNV)
                    .addComponent(rdMKH))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNam)
                    .addComponent(rdThang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(51, 255, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Tổng thu");

        tfTKTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTKTTActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Tổng chi");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Lợi nhuận");

        tfTKLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTKLNActionPerformed(evt);
            }
        });

        btClear.setBackground(new java.awt.Color(0, 153, 153));
        btClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/CLEAR.png"))); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/seo-report.png"))); // NOI18N
        jButton1.setText("Xuất ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTKTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTKTC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tfTKLN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTKTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfTKTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfTKLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClear)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Danh sách chi", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        tbPNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbPNH);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfTKDenNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTKDenNgayActionPerformed
        
    }//GEN-LAST:event_tfTKDenNgayActionPerformed

    private void btTKNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKNgayActionPerformed
        tongThu = 0;
        tongChi = 0;
        if(tfTKTuNgay.getText().length()>0&&tfTKDenNgay.getText().length()>0){
            String tu = tfTKTuNgay.getText();
            String den = tfTKDenNgay.getText();
            if(cbNgay.getSelectedIndex()==1){
                modelhd = new ModelThongKe().getModelhd(tkDTO.thongKeNgayThue(tu, den));
                tbTKHD.setModel(modelhd);
                
                for(int i=0;i<modelhd.getRowCount();i++){
                    tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
                }
                tfTKTT.setText(tongThu+"");

                tfTKTC.setText("");
                tfTKLN.setText("");
            }else{
                if(cbNgay.getSelectedIndex()==0){
                    modelhd = new ModelThongKe().getModelhd(tkDTO.thongKeNgayThanhToan(tu, den));
                    tbTKHD.setModel(modelhd);
                    
                    modelnh = new ModelThongKe().getModelpnh(pnhDTO.danhSachNgayNhap(tu, den));
                    tbPNH.setModel(modelnh);
                    
                    for(int i=0;i<modelhd.getRowCount();i++){
                        tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
                    }
                    tfTKTT.setText(tongThu+"");

                    for(int i=0;i<modelnh.getRowCount();i++){
                        tongChi+=Integer.valueOf(modelnh.getValueAt(i, 2).toString());
                    }
                    tfTKTC.setText(tongChi+"");

                    tfTKLN.setText((Integer.valueOf(tfTKTT.getText())-Integer.valueOf(tfTKTC.getText()))+"");
                }
            }
        }
    }//GEN-LAST:event_btTKNgayActionPerformed

    private void tfTKTuNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTKTuNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTKTuNgayActionPerformed

    private void tfTKTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTKTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTKTTActionPerformed

    private void tfTKLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTKLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTKLNActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed

        tfTKTuNgay.setText("");
        tfTKDenNgay.setText("");
        tfTKMaNhanVien.setText("");
        tfTKMaKhachHang.setText("");
        
        modelhd = new ModelThongKe().getModelhd(tkDTO.thongKe());
        tbTKHD.setModel(modelhd);
        
        modelnh = new ModelThongKe().getModelpnh(pnhDTO.docDanhSachPhieuNhapHang());
        tbPNH.setModel(modelnh);
        
        tongThu = 0;
            tongChi = 0;
            
            for(int i=0;i<modelhd.getRowCount();i++){
                tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
            }
            tfTKTT.setText(tongThu+"");

            for(int i=0;i<modelnh.getRowCount();i++){
                tongChi+=Integer.valueOf(modelnh.getValueAt(i, 2).toString());
            }
            tfTKTC.setText(tongChi+"");

            tfTKLN.setText((Integer.valueOf(tfTKTT.getText())-Integer.valueOf(tfTKTC.getText()))+"");
    }//GEN-LAST:event_btClearActionPerformed

    private void btTKLocNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKLocNhanVienActionPerformed
        tongThu = 0;
        tongChi = 0;
        if(tfTKMaNhanVien.getText().length()>0&&tfTKMaKhachHang.getText().length()>0){
            modelhd = new ModelThongKe().getModelhd(tkDTO.thongKeNhanVienKhachhachHang(tfTKMaNhanVien.getText(),tfTKMaKhachHang.getText()));
            tbTKHD.setModel(modelhd);
            
            for(int i=0;i<modelhd.getRowCount();i++){
                tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
            }
            tfTKTT.setText(tongThu+"");
            tfTKTC.setText("");
        }else{
            if(tfTKMaNhanVien.getText().length()>0){
                modelhd = new ModelThongKe().getModelhd(tkDTO.thongKeNhanVien(tfTKMaNhanVien.getText()));
                tbTKHD.setModel(modelhd);

                modelnh = new ModelThongKe().getModelpnh(pnhDTO.getNhanVien(tfTKMaNhanVien.getText()));
                tbPNH.setModel(modelnh);

                for(int i=0;i<modelhd.getRowCount();i++){
                    tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
                }
                tfTKTT.setText(tongThu+"");

                for(int i=0;i<modelnh.getRowCount();i++){
                    tongChi+=Integer.valueOf(modelnh.getValueAt(i, 2).toString());
                }
                tfTKTC.setText(tongChi+"");
            }else{
                if(tfTKMaKhachHang.getText().length()>0){
                    modelhd = new ModelThongKe().getModelhd(tkDTO.thongKekhachHang(tfTKMaKhachHang.getText()));
                    tbTKHD.setModel(modelhd);

                    for(int i=0;i<modelhd.getRowCount();i++){
                        tongThu+=Integer.valueOf(modelhd.getValueAt(i, 5).toString());
                    }
                    tfTKTT.setText(tongThu+"");

                    tfTKTC.setText("");
                    tfTKLN.setText("");
                }
            }
        }
    }//GEN-LAST:event_btTKLocNhanVienActionPerformed

    private void rdMNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMNVActionPerformed
        modelhd = new ModelThongKe().getModelhd(tkDTO.gomMaNhanVien());
        tbTKHD.setModel(modelhd);
        
        modelnh = new ModelThongKe().getModelpnh(pnhDTO.gomMaNhanVien());
        tbPNH.setModel(modelnh);
    }//GEN-LAST:event_rdMNVActionPerformed

    private void rdMKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMKHActionPerformed
        modelhd = new ModelThongKe().getModelhd(tkDTO.gomMaKhachHang());
        tbTKHD.setModel(modelhd);
    }//GEN-LAST:event_rdMKHActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        modelhd = new ModelThongKe().getModelhd(tkDTO.gomChuoiNgayThangNam(0,4));
        tbTKHD.setModel(modelhd);
        
        modelnh = new ModelThongKe().getModelpnh(pnhDTO.gomChuoiNgayThangNam(0, 4));
        tbPNH.setModel(modelnh);
    }//GEN-LAST:event_rdNamActionPerformed

    private void rdThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThangActionPerformed
        modelhd = new ModelThongKe().getModelhd(tkDTO.gomChuoiNgayThangNam(0,7));
        tbTKHD.setModel(modelhd);
        
        modelnh = new ModelThongKe().getModelpnh(pnhDTO.gomChuoiNgayThangNam(0, 7));
        tbPNH.setModel(modelnh);
    }//GEN-LAST:event_rdThangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vector headerThu = new Vector();
        headerThu.add("Số hóa đơn");
        headerThu.add("Mã nhân viên");
        headerThu.add("Mã khách hàng");
        headerThu.add("Ngày thuê");
        headerThu.add("ngày thanh toán");
        headerThu.add("Tổng tiền");

        Vector headerChi = new Vector();
        headerChi.add("Mã nhân viên");
        headerChi.add("Ngày nhập");
        headerChi.add("Tổng tiền");
        try {
            ReadWriteExcelFile.writeXLSXFile(headerThu,tkDTO.thongKe(),headerChi,pnhDTO.docDanhSachPhieuNhapHang());
        } catch (IOException ex) {
            Logger.getLogger(thongke.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btTKLocNhanVien;
    private javax.swing.JButton btTKNgay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdMKH;
    private javax.swing.JRadioButton rdMNV;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdThang;
    private javax.swing.JTable tbPNH;
    private javax.swing.JTable tbTKHD;
    private javax.swing.JTextField tfTKDenNgay;
    private javax.swing.JTextField tfTKLN;
    private javax.swing.JTextField tfTKMaKhachHang;
    private javax.swing.JTextField tfTKMaNhanVien;
    private javax.swing.JTextField tfTKTC;
    private javax.swing.JTextField tfTKTT;
    private javax.swing.JTextField tfTKTuNgay;
    // End of variables declaration//GEN-END:variables
}
